### ISSUE TITLE
Hope the "onnxruntime" issue is resolved soon！

### ISSUE THREAD

**Issue by yinghanzi** [Fannovel16/comfyui_controlnet_aux#102]
I have been tortured by onnxruntime for a long time recently. The author said it is because CUDA must be 11.8 before it can be used. The current comfyui official version is 12.1, and my system is 12.3. Downgrading to 11.8 is a huge problem. Later, I discovered that there are many plug-ins that use onnxruntime. All the .onnx models, such as was, such as comfyui-reactor-node; I only need to install plug-ins such as comfyui-reactor-node and was in advance, and then install cn, and the problem will be solved. Perfectly solved. If you install controlnet_aux/ first, controlnet_aux/ will mess up everything. This is not my problem alone, many friends are encountering similar problems now!

Since plug-ins such as comfyui-reactor-node can solve this problem, I believe controlnet_aux/ can also do it.

**Comment by yinghanzi** [comment]
There is currently no need to downgrade to cuda11.8, other plug-ins can use onnxruntime normally.

**Comment by Fannovel16** [comment]
@yinghanzi Are you using Windows?

**Comment by murphylanga** [comment]
I have the same problem and use Windows

**Comment by f-rank** [comment]
Getting this on a new comfyui portable install, on windows.

**Comment by Layer-norm** [comment]
Maybe you can disable you GPU acceleration for onnx as reactor-node suggestted https://github.com/Gourieff/comfyui-reactor-node/discussions/73

**Comment by Fannovel16** [comment]
@Layer-norm Opencv already has built-in onnx loader which use CPU by default

**Comment by Layer-norm** [comment]
@Fannovel16 Yes, gpu is much more faster, especially for video. For a 720p video around 300 frames, onnxruntime-gpu only takes about 1 minute to finsh the task, while cpu takes around 1hours. And if you talk about onnxruntime in cpu, I can't tell the difference.

**Comment by murphylanga** [comment]
reactor-node suggestted Gourieff/comfyui-reactor-node#73 -> I can't get it to work since the Comfy update. Additionally I “destroy” the DW-Pose processor. 

At the moment I get the following message:
C:\Spezial\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:24: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")

... , but it works. to create images and is not a problem.

**Comment by Layer-norm** [comment]
I am sorry that onnxruntime-gpu may not support cuda12.3 now. If you wan't to use onnxruntime-gpu in cuda12.x and above in windows, you can try to build it yourself instead of using prebuilt wheel, This link may help you https://onnxruntime.ai/docs/build/eps. And you can find scripts source from [here](https://github.com/microsoft/onnxruntime/tree/Cjian/cuda12_packages). However, it only support cuda version below 12.2 now.

**Comment by tianleiwu** [comment]
To use CUDA 12.* instead of 11.8, you can try install nightly binary like the following:
```
pip install ort-nightly-gpu --index-url=https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ort-cuda-12-nightly/pypi/simple/
```

**Comment by Layer-norm** [comment]
@f-rank @tianleiwu @murphylanga 
onnxrutime-gpu support cuda12 now.
YOU SHOULD REMOVE THE OLD VERSION COMPLETELY
`pip uninstall onnxruntime onnxruntime-gpu` and remove **onnxruntime** folder in (your python folder)/Lib/site-packages if it exists after uninstall.
Then `pip install -U onnx onnxruntime onnxruntime-gpu`
after that you can use onnx model with your gpu in cuda12 now.
请先完全卸载onnxruntime onnxruntime-gpu
并在卸载后确认python embeded/Lib/site-packages文件夹里是否有onnxruntime文件夹残留
如果有请将整个onnxruntime文件夹扔进回收站（命令可能卸载不干净）
然后重新安装onnx onnxruntine onnxruntime-gpu
 `python -m pip install -U onnx onnxruntime onnxruntime-gpu`

**Comment by murphylanga** [comment]
👍 Thank you so much for your assistance in solving the problem. 

Unfortunately, the Ultimate Upscale Node crashes now when it comes after the Control Net Openpose in a workflow.

**Comment by escalate007** [comment]
> @f-rank @tianleiwu @murphylanga onnxrutime-gpu support cuda12 now. YOU SHOULD REMOVE THE OLD VERSION COMPLETELY `pip uninstall onnxruntime onnxruntime-gpu` and remove **onnxruntime** folder in (your python folder)/Lib/site-packages if it exists after uninstall. Then `pip install -U onnx onnxruntime onnxruntime-gpu` after that you can use onnx model with your gpu in cuda12 now. 请先完全卸载onnxruntime onnxruntime-gpu 并在卸载后确认python embeded/Lib/site-packages文件夹里是否有onnxruntime文件夹残留 如果有请将整个onnxruntime文件夹扔进回收站（命令可能卸载不干净） 然后重新安装onnx onnxruntine onnxruntime-gpu `python -m pip install -U onnx onnxruntime onnxruntime-gpu`

非常感谢，困扰我3个小时的问题，各种找解决方案，这个最有效。
我的controlnet插件没出问题，是rembg移除背景的插件报错。

**Comment by tianleiwu** [comment]
`python -m pip install -U onnx onnxruntime onnxruntime-gpu` is the right way. It installs ORT for CUDA 11, not for CUDA 12. Also, there is no need to install onnxruntime package (it is CPU only), which might overwrite the gpu package.

Please make sure you only install one ORT package (like onnxruntime, onnxruntime-gpu or nightly variants). It is because all those packages will be installed to same onnxruntime subdirectory under site-packages (run `pip show onnxruntime-gpu` to see the site-package location). 

Sometime, the issue is caused by some dependency (like VC Runtime, CUDA and cuDNN) not installed. Please follow https://onnxruntime.ai/docs/install/ to install onnxruntime-gpu for CUDA 12 for detail. The command to install official package is like the following:
```
pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
```

**Comment by shivshankar11** [comment]
for late comer:
here's the way to enable gpu accelerate on cuda12.x

track the issue here for version changes: https://github.com/microsoft/onnxruntime/issues/13932
runtime nightly: https://dev.azure.com/onnxruntime/onnxruntime/_artifacts/feed/onnxruntime-cuda-12
ort nightly:https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ort-cuda-12-nightly

#with cu12.*
pip install coloredlogs flatbuffers numpy packaging protobuf sympy
pip install ort-nightly-gpu --index-url=https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ort-cuda-12-nightly/pypi/simple/
pip install onnxruntime-gpu==1.17.0 --index-url=https://pkgs.dev.azure.com/onnxruntime/onnxruntime/_packaging/onnxruntime-cuda-12/pypi/simple/

**Comment by maderisna** [comment]
need help i got this error :

DWPose: Using yolox_l.onnx for bbox detection and dw-ll_ucoco_384_bs5.torchscript.pt for pose estimation
DWPose: Caching ONNXRuntime session yolox_l.onnx...
2024-11-29 08:40:04.1171188 [E:onnxruntime:Default, provider_bridge_ort.cc:1745 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\User\Desktop\ComfyUI MHD 3.0\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:891 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-11-29 08:40:04.2046481 [E:onnxruntime:Default, provider_bridge_ort.cc:1745 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\User\Desktop\ComfyUI MHD 3.0\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

!!! Exception during processing !!! 'NoneType' object has no attribute 'get_providers'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:891 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\wholebody.py", line 39, in __init__
    self.det = ort.InferenceSession(det_model_path, providers=ort_providers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 432, in __init__
    raise fallback_error from e
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 427, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:891 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 72, in estimate_pose
    model = DwposeDetector.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\__init__.py", line 238, in from_pretrained
    t = Wholebody(det_model_path, None, torchscript_device=torchscript_device)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\wholebody.py", line 41, in __init__
    print(f"Failed to load onnxruntime with {self.det.get_providers()}.\nPlease change EP_list in the config.yaml and restart ComfyUI")
                                             ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_providers'

**Comment by maderisna** [comment]
need help, i got this error

DWPose: Using yolox_l.onnx for bbox detection and dw-ll_ucoco_384_bs5.torchscript.pt for pose estimation
DWPose: Caching ONNXRuntime session yolox_l.onnx...
2024-11-29 08:40:04.1171188 [E:onnxruntime:Default, provider_bridge_ort.cc:1745 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\User\Desktop\ComfyUI MHD 3.0\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:891 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-11-29 08:40:04.2046481 [E:onnxruntime:Default, provider_bridge_ort.cc:1745 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\User\Desktop\ComfyUI MHD 3.0\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

!!! Exception during processing !!! 'NoneType' object has no attribute 'get_providers'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:891 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\wholebody.py", line 39, in __init__
    self.det = ort.InferenceSession(det_model_path, providers=ort_providers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 432, in __init__
    raise fallback_error from e
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 427, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:891 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 72, in estimate_pose
    model = DwposeDetector.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\__init__.py", line 238, in from_pretrained
    t = Wholebody(det_model_path, None, torchscript_device=torchscript_device)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\ComfyUI MHD 3.0\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\wholebody.py", line 41, in __init__
    print(f"Failed to load onnxruntime with {self.det.get_providers()}.\nPlease change EP_list in the config.yaml and restart ComfyUI")
                                             ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_providers'
