### ISSUE TITLE
Latest commit broke all my annotators

### ISSUE THREAD

**Issue by AmusedDiffuser** [Fannovel16/comfyui_controlnet_aux#11]
Various errors, all relating to cv2 not having the specified modules (?) that were being called.

As I had updated many different things at once, spent hours troubleshooting thinking it was something else, reinstalling OpenCV-Python, Numpy, PIP... Finally tried rolling this repo back to previous commit and all problems are gone now (though I can't run the new LoRA ControlNets but I see no reason yet to think that's related).

Not at my computer anymore but I do still have many of the error messages on screen which I'll add later both for general information and so others can find this post/solution if they have the same errors.

General info:
GTX-1660 ti 6gb vRAM
Windows 11

**Comment by katopz** [comment]
Confirm breaking `No module named 'cv2'`
```
Adding extra search path controlnet /sd/stable-diffusion-webui\models/ControlNet
Traceback (most recent call last):
  File "C:\sd\comfyui\ComfyUI\nodes.py", line 1688, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\sd\comfyui\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 2, in <module>
    from .utils import here
  File "C:\sd\comfyui\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 4, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import C:\sd\comfyui\ComfyUI\custom_nodes\comfyui_controlnet_aux module for custom nodes: No module named 'cv2'
```
Try `pip install opencv-python` and still no joy.
```
Requirement already satisfied: opencv-python in c:\users\foo\appdata\local\programs\python\python310\lib\site-packages (4.8.0.76)
Requirement already satisfied: numpy>=1.21.2 in c:\users\foo\appdata\local\programs\python\python310\lib\site-packages (from opencv-python) (1.24.3)
DEPRECATION: pytorch-lightning 1.7.7 has a non-standard dependency specifier torch>=1.9.*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pytorch-lightning or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063     
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
```

**Comment by katopz** [comment]
FYI: this working for me now
```
 C:\sd\comfyui\python_embeded> .\python.exe .\Scripts\pip.exe install opencv-python
```
