### ISSUE TITLE
Error: 'cv2.gapi.wip.draw' has no attribute 'Text' 

### ISSUE THREAD

**Issue by anagilabs** [Fannovel16/comfyui_controlnet_aux#125]
Hi, were you able to fix the issue, i am getting the same error: 

Device: cuda:0 NVIDIA GeForce RTX 3050 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Torch version: 2.1.0+cu121
Traceback (most recent call last):
  File "C:\Users\us\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\us\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 2, in <module>
    from .utils import here, create_node_input_types
  File "C:\Users\us\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 4, in <module>
    import cv2
  File "C:\Users\us\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\us\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\us\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "C:\Users\us\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cv2\typing\__init__.py", line 157, in <module>
    Prim = typing.Union[cv2.gapi.wip.draw.Text, cv2.gapi.wip.draw.Circle, cv2.gapi.wip.draw.Image, cv2.gapi.wip.draw.Line, cv2.gapi.wip.draw.Rect, cv2.gapi.wip.draw.Mosaic, cv2.gapi.wip.draw.Poly]
                        ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'cv2.gapi.wip.draw' has no attribute 'Text'

Cannot import C:\Users\us\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux module for custom nodes: module 'cv2.gapi.wip.draw' has no attribute 'Text'

Import times for custom nodes:
   0.0 seconds: C:\Users\us\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\canvas_tab
   0.0 seconds: C:\Users\us\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-tooling-nodes
   0.0 seconds: C:\Users\us\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\Users\us\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds (IMPORT FAILED): C:\Users\us\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux

searched hours on internet, tried all the suggestions given for this issue, not to mention those suggested on comfyui_controlnet_aux github repo page, still getting the error

_Originally posted by @anagilabs in https://github.com/Fannovel16/comfyui_controlnet_aux/issues/105#issuecomment-1820553492_

**Comment by anagilabs** [comment]
apparently 'Reactor' custom node has been causing this issue, after uninstalling reactor custom node, it works. However, after installing comfyui-impack-node, both work, atleast dont get [IMPORT FAILED] error.. cant figure out why so!

**Comment by Fannovel16** [comment]
@skylerblack2 @anagilabs Try this solution https://github.com/Gourieff/comfyui-reactor-node#iv-controlnet-aux-node-import-failed-error-when-using-with-reactor-node
