### ISSUE TITLE
Menu does not show up in Portal version of ComfyUI

### ISSUE THREAD

**Issue by sturentz** [Fannovel16/comfyui_controlnet_aux#128]
I think I see similar issues with no solutions yet. Tried:

1. Installing via the Manager
2.  Manually

While the CMD line packages do install, when relaunching Comfy the preprocessor menu isn't there, and there is no way to access them through the ComfyUI interface. Other things do install from the packaged manager, so it isn't a general package manager issue.

Windows 11
ComfyUI portable

Help appreciated.

**Comment by Fannovel16** [comment]
@sturentz If an extension is installed but doesn't show up on the menu, ComfyUI failed to import it. You can launch ComfyUI then post the log on CMD so I can see why that happens

**Comment by sturentz** [comment]
Hi, - thank you for your response. I had to do a clean install a few times to catch which custom node is the conflict.  Any insight to the below is appreciated.

The issue seems to be the co-existence of ControlNet and Reactor https://github.com/Gourieff/comfyui-reactor-node which when it is installed makes Controlnet/preprocessors menu not show up (and controlnet fails to load).

Traceback (most recent call last):
  File "D:\ai3\ComfyUI_Mixime6d\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai3\ComfyUI_Mixime6d\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 2, in <module>
    from .utils import here, create_node_input_types
  File "D:\ai3\ComfyUI_Mixime6d\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 4, in <module>
    import cv2
  File "D:\ai3\ComfyUI_Mixime6d\python_embeded\Lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "D:\ai3\ComfyUI_Mixime6d\python_embeded\Lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai3\ComfyUI_Mixime6d\python_embeded\Lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "D:\ai3\ComfyUI_Mixime6d\python_embeded\Lib\site-packages\cv2\typing\__init__.py", line 157, in <module>
    Prim = typing.Union[cv2.gapi.wip.draw.Text, cv2.gapi.wip.draw.Circle, cv2.gapi.wip.draw.Image, cv2.gapi.wip.draw.Line, cv2.gapi.wip.draw.Rect, cv2.gapi.wip.draw.Mosaic, cv2.gapi.wip.draw.Poly]
                        ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'cv2.gapi.wip.draw' has no attribute 'Text'

Cannot import D:\ai3\ComfyUI_Mixime6d\ComfyUI\custom_nodes\comfyui_controlnet_aux module for custom nodes: module 'cv2.gapi.wip.draw' has no attribute 'Text'
Total VRAM 6144 MB, total RAM 32698 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync
VAE dtype: torch.float32
Traceback (most recent call last):
  File "D:\ai3\ComfyUI_Mixime6d\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai3\ComfyUI_Mixime6d\ComfyUI\custom_nodes\facerestore_cf\__init__.py", line 6, in <module>
    import cv2
  File "D:\ai3\ComfyUI_Mixime6d\python_embeded\Lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "D:\ai3\ComfyUI_Mixime6d\python_embeded\Lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai3\ComfyUI_Mixime6d\python_embeded\Lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "D:\ai3\ComfyUI_Mixime6d\python_embeded\Lib\site-packages\cv2\typing\__init__.py", line 157, in <module>
    Prim = typing.Union[cv2.gapi.wip.draw.Text, cv2.gapi.wip.draw.Circle, cv2.gapi.wip.draw.Image, cv2.gapi.wip.draw.Line, cv2.gapi.wip.draw.Rect, cv2.gapi.wip.draw.Mosaic, cv2.gapi.wip.draw.Poly]
                        ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'cv2.gapi.wip.draw' has no attribute 'Text'

Cannot import D:\ai3\ComfyUI_Mixime6d\ComfyUI\custom_nodes\facerestore_cf module for custom nodes: module 'cv2.gapi.wip.draw' has no attribute 'Text'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): D:\ai3\ComfyUI_Mixime6d\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds (IMPORT FAILED): D:\ai3\ComfyUI_Mixime6d\ComfyUI\custom_nodes\facerestore_cf
   0.3 seconds: D:\ai3\ComfyUI_Mixime6d\ComfyUI\custom_nodes\ComfyUI-Manager
   0.7 seconds: D:\ai3\ComfyUI_Mixime6d\ComfyUI\custom_nodes\comfyui-reactor-node

**Comment by Fannovel16** [comment]
If you are using ComfyUI portable, open CMD and cd to `D:\ai3\ComfyUI_Mixime6d` then execute
```
python_embeded\python.exe -m pip uninstall -y opencv-python opencv-contrib-python opencv-python-headless python_embeded\python.exe -m pip install opencv-python==4.7.0.72
```

**Comment by sturentz** [comment]
yes, this worked. sorry if I missed this when searching for solutions. Thank you for your help!
