### ISSUE TITLE
module 'cv2.gapi.wip.draw' has no attribute 'Text' when using comfyui-reactor-node

### ISSUE THREAD

**Issue by mkvt141** [Fannovel16/comfyui_controlnet_aux#133]
When I'm using comfyui-reactor-node, then comfyui_controlnet_aux fails to load giving me "Cannot import /Users/marek/ComfyUI/custom_nodes/comfyui_controlnet_aux module for custom nodes: module 'cv2.gapi.wip.draw' has no attribute 'Text'"

When I disable comfyui-reactor-node, then comfyui_controlnet_aux loads fine.

`** ComfyUI start up time: 2023-11-29 23:33:07.813969

Prestartup times for custom nodes:
   0.0 seconds: /Users/marek/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 65536 MB, total RAM 65536 MB
Forcing FP16.
Set vram state to: SHARED
Device: mps
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
### ComfyUI Revision: 1748 [a6676384] | Released on '2023-11-27'
Total VRAM 65536 MB, total RAM 65536 MB
Forcing FP16.
Set vram state to: SHARED
Device: mps
VAE dtype: torch.float32
Torch version: 2.1.1
Traceback (most recent call last):
  File "/Users/marek/ComfyUI/nodes.py", line 1798, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/marek/ComfyUI/custom_nodes/comfyui_controlnet_aux/__init__.py", line 2, in <module>
    from .utils import here, create_node_input_types
  File "/Users/marek/ComfyUI/custom_nodes/comfyui_controlnet_aux/utils.py", line 4, in <module>
    import cv2
  File "/Users/marek/.pyenv/versions/3.10.9/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/Users/marek/.pyenv/versions/3.10.9/lib/python3.10/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/Users/marek/.pyenv/versions/3.10.9/lib/python3.10/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/Users/marek/.pyenv/versions/3.10.9/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/marek/.pyenv/versions/3.10.9/lib/python3.10/site-packages/cv2/typing/__init__.py", line 157, in <module>
    Prim = typing.Union[cv2.gapi.wip.draw.Text, cv2.gapi.wip.draw.Circle, cv2.gapi.wip.draw.Image, cv2.gapi.wip.draw.Line, cv2.gapi.wip.draw.Rect, cv2.gapi.wip.draw.Mosaic, cv2.gapi.wip.draw.Poly]
AttributeError: module 'cv2.gapi.wip.draw' has no attribute 'Text'

Cannot import /Users/marek/ComfyUI/custom_nodes/comfyui_controlnet_aux module for custom nodes: module 'cv2.gapi.wip.draw' has no attribute 'Text'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): /Users/marek/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.0 seconds: /Users/marek/ComfyUI/custom_nodes/ComfyUI-Manager
   0.4 seconds: /Users/marek/ComfyUI/custom_nodes/comfyui-reactor-node

Starting server

To see the GUI go to: http://127.0.0.1:8188

`

**Comment by anthonyaquino83** [comment]
Same here.

**Comment by mkvt141** [comment]
> Update your comfyui-reactor-node and reinstall opencv-python package(uninstall it first). Please note that it is `pip install opencv-python` instead of `pip install cv2`.

Thank you for the suggestion. I did:
- "Update All" from Comfy UI manager menu
- pip uninstall opencv-python
- pip install opencv-python

Unfortunately still same result:
`marek@Mareks-MacBook-Pro ComfyUI % python main.py --force-fp16
** ComfyUI start up time: 2023-12-05 07:21:48.198266

Prestartup times for custom nodes:
   0.0 seconds: /Users/marek/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 65536 MB, total RAM 65536 MB
Forcing FP16.
Set vram state to: SHARED
Device: mps
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
### Loading: ComfyUI-Manager (V1.6.4)
### ComfyUI Revision: 1779 [9b655d4f] | Released on '2023-12-04'
Total VRAM 65536 MB, total RAM 65536 MB
Forcing FP16.
Set vram state to: SHARED
Device: mps
VAE dtype: torch.float32
Torch version: 2.1.1
Traceback (most recent call last):
  File "/Users/marek/ComfyUI/nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/marek/ComfyUI/custom_nodes/comfyui_controlnet_aux/__init__.py", line 2, in <module>
    from .utils import here, create_node_input_types
  File "/Users/marek/ComfyUI/custom_nodes/comfyui_controlnet_aux/utils.py", line 4, in <module>
    import cv2
  File "/Users/marek/.pyenv/versions/3.10.9/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/Users/marek/.pyenv/versions/3.10.9/lib/python3.10/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/Users/marek/.pyenv/versions/3.10.9/lib/python3.10/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/Users/marek/.pyenv/versions/3.10.9/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/marek/.pyenv/versions/3.10.9/lib/python3.10/site-packages/cv2/typing/__init__.py", line 157, in <module>
    Prim = typing.Union[cv2.gapi.wip.draw.Text, cv2.gapi.wip.draw.Circle, cv2.gapi.wip.draw.Image, cv2.gapi.wip.draw.Line, cv2.gapi.wip.draw.Rect, cv2.gapi.wip.draw.Mosaic, cv2.gapi.wip.draw.Poly]
AttributeError: module 'cv2.gapi.wip.draw' has no attribute 'Text'

Cannot import /Users/marek/ComfyUI/custom_nodes/comfyui_controlnet_aux module for custom nodes: module 'cv2.gapi.wip.draw' has no attribute 'Text'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): /Users/marek/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.0 seconds: /Users/marek/ComfyUI/custom_nodes/ComfyUI-Manager
   1.0 seconds: /Users/marek/ComfyUI/custom_nodes/comfyui-reactor-node

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: /Users/marek/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json

`

**Comment by Layer-norm** [comment]
That's wired, It`s just `import cv2` 
make sure you at the same python enviroment as comfyui. try these code:
`cd /Users/marek/.pyenv/versions/3.10.9/bin/`
`python -m pip uninstall -y opencv-python opencv-contrib-python opencv-python-headless`
`python -m pip install opencv-python==4.7.0.72` or `python -m pip install opencv-python==4.8.1.78`

**Comment by Layer-norm** [comment]
That's wired. it's just `import cv2`
Are you sure you did my suggestion at the **same** **pyenv** as ComfyUI?
try these:
`cd /Users/marek/.pyenv/versions/3.10.9/bin/`
`python -m pip uninstall -y opencv-python opencv-contrib-python opencv-python-headless`
`python -m pip install opencv-python==4.8.1.78` or `python -m pip install opencv-python==4.7.0.72`

**Comment by mkvt141** [comment]
> python -m pip install opencv-python==4.8.1.78

Thank you so much!

`python -m pip install opencv-python==4.8.1.78` did not help

but `python -m pip install opencv-python==4.7.0.72` **worked!**

**Comment by rovo79** [comment]
> python -m pip install opencv-python==4.8.1.78 did not help
> 
> but python -m pip install opencv-python==4.7.0.72 worked!

@mkvt141  Same for me! 

Python version: 3.11.5
Torch version: 2.1.0
