### ISSUE TITLE
DWpose fails to load

### ISSUE THREAD

**Issue by 49RpK5dY** [Fannovel16/comfyui_controlnet_aux#135]
DWpose fails to load since the last update. I'm running in a docker container with python: 3.9.5 and torch: 1.13.0+rocm5.2 if that makes a difference.

Here's the log:

```
Full error log from comfyui_controlnet_aux:
Traceback (most recent call last):
  File "/sd/ComfyUI/custom_nodes/comfyui_controlnet_aux/__init__.py", line 32, in load_nodes
    module = importlib.import_module(
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/sd/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py", line 5, in <module>
    from controlnet_aux.dwpose import DwposeDetector, AnimalposeDetector
  File "/sd/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/dwpose/__init__.py", line 23, in <module>
    from .wholebody import Wholebody
  File "/sd/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/dwpose/wholebody.py", line 35
    match self.det_model_type:
          ^
SyntaxError: invalid syntax



[comfyui_controlnet_aux] | INFO -> Some nodes failed to load:
	Failed to import module dwpose because SyntaxError: invalid syntax
```

**Comment by Fannovel16** [comment]
@49RpK5dY I thought everyone have moved out to python 3.10

**Comment by 49RpK5dY** [comment]
Thanks for the quick fix. There is pretty much a single docker image that works with my gpu based on ubuntu20.04 and it has python 3.9.5.
