### ISSUE TITLE
Failed to import module dwpose

### ISSUE THREAD

**Issue by vladmartin41** [Fannovel16/comfyui_controlnet_aux#136]
DWpose node disappeared after update with that error. I use portable ComfyUI, last version.

```
Full error log from comfyui_controlnet_aux: 
Traceback (most recent call last):
  File "F:\SD\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 32, in load_nodes
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\SD\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 5, in <module>
    from controlnet_aux.dwpose import DwposeDetector, AnimalposeDetector
  File "F:\SD\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\__init__.py", line 152, in <module>
    global_cached_dwpose = Wholebody()
                           ^^^^^^^^^^^
  File "F:\SD\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\wholebody.py", line 26, in __init__
    self.det_model_type = get_model_type("DWPose",self.det_filename)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\SD\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\util.py", line 446, in get_model_type
    ort_providers = list(filter(lambda x : x != "CPUExecutionProvider", get_ort_providers()))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

**Comment by alanhzh** [comment]
They changed name:

>>> help(dwpose)
Help on package controlnet_aux.dwpose in controlnet_aux:

NAME
    controlnet_aux.dwpose

DESCRIPTION
    # Openpose
    # Original from CMU https://github.com/CMU-Perceptual-Computing-Lab/openpose
    # 2nd Edited by https://github.com/Hzzone/pytorch-openpose
    # 3rd Edited by ControlNet
    # 4th Edited by ControlNet (added face and correct hands)

PACKAGE CONTENTS
    util
    wholebody

CLASSES
    builtins.object
        DWposeDetector
