### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by mcxdiy** [Fannovel16/comfyui_controlnet_aux#143]
[comfyui_controlnet_aux-main] | INFO -> Some nodes failed to load:
        Failed to import module anime_face_segment because ImportError: cannot import name 'ANIFACESEG_MODEL_NAME' from 'comfyui_controlnet_aux-main.utils' (E:\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux-main\utils.py)

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/Fannovel16/comfyui_controlnet_aux/issues)
Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes\__init__.py", line 57, in <module>
    from .ScheduledNodes import ValueSchedule, PromptSchedule, PromptScheduleNodeFlow, PromptScheduleNodeFlowEnd, PromptScheduleEncodeSDXL, StringSchedule, BatchPromptSchedule, BatchValueSchedule, BatchPromptScheduleEncodeSDXL #, BatchGLIGENSchedule
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduledNodes.py", line 4, in <module>
    import numexpr
ModuleNotFoundError: No module named 'numexpr'

Cannot import E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes module for custom nodes: No module named 'numexpr'
Efficiency Nodes: Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...Failed!
Efficiency Nodes Warning: Failed to import python package 'simpleeval'; related nodes disabled.

**Comment by xybear1966** [comment]
i have that error, but I also have 
"Cannot import /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes module for custom nodes: Detected that PyTorch and torchvision were compiled with different CUDA major versions. PyTorch has CUDA Version=12.1 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install."  pops up all through the install process.
running comfy on colab.  most important missing node for me is the manager
