### ISSUE TITLE
ImportError: attempted relative import beyond top-level package

### ISSUE THREAD

**Issue by d8ahazard** [Fannovel16/comfyui_controlnet_aux#15]
Seems as if using the relative pathing for the HWC3/resize_image import is not working properly.

Using Ubuntu 22.

Traceback (most recent call last):
  File "/home/apps/ComfyUI/nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/apps/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/__init__.py", line 66, in <module>
    import impact.impact_server  # to load server api
  File "/home/apps/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_server.py", line 10, in <module>
    import impact.core as core
  File "/home/apps/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 2, in <module>
    from segment_anything import SamPredictor
  File "/home/apps/ComfyUI/custom_nodes/comfy_controlnet_aux/src/controlnet_aux/segment_anything/__init__.py", line 17, in <module>
    from ..util import HWC3, resize_image
ImportError: attempted relative import beyond top-level package

Cannot import /home/apps/ComfyUI/custom_nodes/ComfyUI-Impact-Pack module for custom nodes: attempted relative import beyond top-level package

**Comment by d8ahazard** [comment]
OK, so, did some more homework, and I guess there's really nothing wrong with this package, per-se.

However, when loaded in conjunction with the ComfyUI Impact Pack, the other module gets confused because it's trying to import your segment_anything module, versus the one from Pypi. As such, I'd humbly suggest re-naming it so this isn't an issue.
