### ISSUE TITLE
 ComfyUI - Control Net Aux - ModuleNotFoundError: No module named 'cv2' 

### ISSUE THREAD

**Issue by MarcinSoj** [Fannovel16/comfyui_controlnet_aux#153]
Hi everyone. I have problem with control net . It is brand new version : ComfyUI_windows_portable_nvidia_or_cpu_nightly_pytorch.7z from official github repository. I have extracted it and used : update_comfyui_and_python_dependencies.bat. After update it says that everything passed and has been updated. When i start WebUI it shows me this message:

ComfyUI Revision: 1833 [https://github.com/comfyanonymous/ComfyUI/commit/6453dc1ca2d98d89af7cf312bb48d1e3fd2ca27f] | Released on '2023-12-16'

Traceback (most recent call last):
File "c:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\nodes.py", line 1800, in load_custom_node
module_spec.loader.exec_module(module)
File "", line 994, in exec_module
File "", line 488, in call_with_frames_removed
File "C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\comfyui_controlnet_aux_init.py", line 2, in
from .utils import here, create_node_input_types
File "C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 4, in
import cv2
ModuleNotFoundError: No module named 'cv2'

FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.jsonCannot import C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\comfyui_controlnet_aux module for custom nodes:
No module named 'cv2'
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Failed!
Efficiency Nodes Warning: Failed to import python package 'simpleeval'; related nodes disabled.

Import times for custom nodes:
0.0 seconds: C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\sdxl-recommended-res-calc
0.0 seconds: C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI_SimpleMath
0.0 seconds: C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
0.0 seconds: C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyMath
0.0 seconds (IMPORT FAILED): C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\comfyui_controlnet_aux
0.0 seconds: C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
0.0 seconds: C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\efficiency-nodes-comfyui
0.5 seconds: C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Manager

My config is : .\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --lowvram --preview-method auto --disable-cuda-malloc --bf16-vae --fp8_e4m3fn-unet

I tried to copy missing files : opencv_contrib_python-4.8.0.76.dist-info , opencv_python_headless-4.8.0.76.dist-info and opencv_python-4.8.0.76.dist-info but it does not do anything.

The other thing is also that in site-packages i cannot see files for: controlnet_aux. I can find controlnet_aux and controlnet_aux-0.0.6.dist-info in my Python 3.10 in c:\Python310\Lib\site-packages. But they are not in : c:\ComfyUI_windows_portable_nightly_pytorch\python_embeded\Lib\site-packages.

Maybe there is someone who can investigate this more.

Thank you for help.

p.s. Hi i have made by mistake issue in ComfyUI tread about this problem. [https://github.com/comfyanonymous/ComfyUI/issues/2310 ](url)

**Comment by Thamimtommy** [comment]
Run this command to install the opencv "pip install opencv-python"
