### ISSUE TITLE
DW-Pose not loading

### ISSUE THREAD

**Issue by ShadoW-Shinigami** [Fannovel16/comfyui_controlnet_aux#161]
Full error log from comfyui_controlnet_aux:
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 32, in load_nodes
    module = importlib.import_module(
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 5, in <module>
    from controlnet_aux.dwpose import DwposeDetector, AnimalposeDetector
ImportError: cannot import name 'DwposeDetector' from 'controlnet_aux.dwpose' (D:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\controlnet_aux\dwpose\__init__.py)

[comfyui_controlnet_aux] | INFO -> Some nodes failed to load:
        Failed to import module dwpose because ImportError: cannot import name 'DwposeDetector' from 'controlnet_aux.dwpose' (D:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\controlnet_aux\dwpose\__init__.py)

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/Fannovel16/comfyui_controlnet_aux/issues)
[comfyui_controlnet_aux] | INFO -> Some nodes failed to load:
        Failed to import module dwpose because ImportError: cannot import name 'DwposeDetector' from 'controlnet_aux.dwpose' (D:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\controlnet_aux\dwpose\__init__.py)

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/Fannovel16/comfyui_controlnet_aux/issues)

Tried reinstalling all dependencies as well. Still does not work. Throws the same error

**Comment by tdw-hyn** [comment]
sa

**Comment by tdw-hyn** [comment]
same question

**Comment by ricardofeynman** [comment]
I'm getting this:

Full error log from comfyui_controlnet_aux: 
Traceback (most recent call last):
  File "/home/x/Documents/_ComfyUI_2023-11-25_1735C/ComfyUI/custom_nodes/comfyui_controlnet_aux/__init__.py", line 32, in load_nodes
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/miniconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/x/Documents/_ComfyUI_2023-11-25_1735C/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py", line 5, in <module>
    from controlnet_aux.dwpose import DwposeDetector, AnimalposeDetector
ImportError: cannot import name 'DwposeDetector' from 'controlnet_aux.dwpose' (/home/x/miniconda3/lib/python3.11/site-packages/controlnet_aux/dwpose/__init__.py)



Loaded ControlNetPreprocessors nodes from /home/x/Documents/_ComfyUI_2023-11-25_1735C/ComfyUI/custom_nodes/comfyui_controlnet_aux


Any ideas?

**Comment by ricardofeynman** [comment]
Found this in the closed issues. Worked for me https://github.com/Fannovel16/comfyui_controlnet_aux/issues/158
