### ISSUE TITLE
“File loading is not yet supported on Windows ”Windows 10 Professional Edition reports an error when running this Meshgraphomer-DepthMapPreprocessor. I don't know how to solve it.

### ISSUE THREAD

**Issue by PLFENG** [Fannovel16/comfyui_controlnet_aux#183]
Error occurred when executing MeshGraphormer-DepthMapPreprocessor:

File loading is not yet supported on Windows

  File "E:\ComfyUI\Blender_ComfyUI\ComfyUI\execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\ComfyUI\Blender_ComfyUI\ComfyUI\execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\ComfyUI\Blender_ComfyUI\ComfyUI\execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\mesh_graphormer.py", line 57, in execute
    model = MeshGraphormerDetector.from_pretrained().to(model_management.get_torch_device())
  File "E:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\mesh_graphormer\__init__.py", line 15, in from_pretrained
    pipeline = MeshGraphormerMediapipe(args)
  File "E:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\mesh_graphormer\pipeline.py", line 201, in __init__
    self.detector = vision.HandLandmarker.create_from_options(options)
  File "E:\ComfyUI\Blender_ComfyUI\python_embeded\lib\site-packages\mediapipe\tasks\python\vision\hand_landmarker.py", line 271, in create_from_options
    return cls(
  File "E:\ComfyUI\Blender_ComfyUI\python_embeded\lib\site-packages\mediapipe\tasks\python\vision\core\base_vision_task_api.py", line 66, in __init__
    self._runner = _TaskRunner.create(graph_config, packet_callback)

**Comment by Fannovel16** [comment]
@PLFENG Try upgrading mediapipe to the latest version by running this commnand:
```cmd
E:\ComfyUI\Blender_ComfyUI\python_embeded\python -s -m pip install --upgrade mediapipe
```

**Comment by DivinoAG** [comment]
> @PLFENG Try upgrading mediapipe to the latest version by running this commnand:
> 
> ```batchfile
> E:\ComfyUI\Blender_ComfyUI\python_embeded\python -s -m pip install --upgrade mediapipe
> ```

I'm also having the same issue, and running this command did not solve the problem for me.

I am using a portable version of ComfyUI, and tried installing the plugin from Manager, and also tried downloading the repo as a ZIP file and running the `install.bat` file. Neither made any difference, the exact same problem persists. The following is the full error message on the shell:

```shell
set os.environ[OMP_NUM_THREADS] to 4
=> loading pretrained model C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux-main\ckpts\hr16/ControlNet-HandRefiner-pruned\hrnetv2_w64_imagenet_pretrained.pth
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux-main\node_wrappers\mesh_graphormer.py", line 84, in execute
    model = MeshGraphormerDetector.from_pretrained().to(model_management.get_torch_device())
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux-main\src\controlnet_aux\mesh_graphormer\__init__.py", line 16, in from_pretrained
    pipeline = MeshGraphormerMediapipe(args)
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux-main\src\controlnet_aux\mesh_graphormer\pipeline.py", line 201, in __init__
    self.detector = vision.HandLandmarker.create_from_options(options)
  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\mediapipe\tasks\python\vision\hand_landmarker.py", line 271, in create_from_options
    return cls(
  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\mediapipe\tasks\python\vision\core\base_vision_task_api.py", line 66, in __init__
    self._runner = _TaskRunner.create(graph_config, packet_callback)
RuntimeError: File loading is not yet supported on Windows
```

**Comment by Layer-norm** [comment]
I tested some kinds of python environment on Windows: 64bit installer version, venv, embedded version and conda. They all have this issue.
Here are two workflows look the same, but one work while the other not.
![work](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/140777998/577527b1-ea27-4e8f-9804-dde42b5b4a71)

![meshgraphomer](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/140777998/c584c097-781a-4c64-a61d-3e0dc584f449)

Besides, I tried to print **graph_config** value with codes below:
```
with open('I:\\ComfyUI\\graph_config.txt', 'w') as f:
    f.write(str(graph_config))

self._runner = _TaskRunner.create(graph_config, packet_callback)
```
And the values are same:
```
node {
  calculator: "mediapipe.tasks.vision.hand_landmarker.HandLandmarkerGraph"
  input_stream: "IMAGE:image_in"
  input_stream: "NORM_RECT:norm_rect_in"
  output_stream: "HANDEDNESS:handedness"
  output_stream: "LANDMARKS:landmarks"
  output_stream: "WORLD_LANDMARKS:world_landmarks"
  output_stream: "IMAGE:image_out"
  options {
    [mediapipe.tasks.vision.hand_landmarker.proto.HandLandmarkerGraphOptions.ext] {
      base_options {
        model_asset {
          file_name: "I:\\ComfyUI\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\controlnet_aux\\mesh_graphormer\\hand_landmarker.task"
        }
        use_stream_mode: false
      }
      hand_detector_graph_options {
        min_detection_confidence: 0.6
        num_hands: 2
      }
      hand_landmarks_detector_graph_options {
        min_detection_confidence: 0.6
      }
      min_tracking_confidence: 0.6
    }
  }
}
input_stream: "IMAGE:image_in"
input_stream: "NORM_RECT:norm_rect_in"
output_stream: "HANDEDNESS:handedness"
output_stream: "LANDMARKS:landmarks"
output_stream: "WORLD_LANDMARKS:world_landmarks"
output_stream: "IMAGE:image_out"
```
Just as this error message indicates: File loading is not yet supported on Windows.

**Comment by PaulWolfgang** [comment]
It seems to be an upstream issue, see:
https://github.com/google/mediapipe/issues/4983#issuecomment-1878081429
The solution in the comments solved my problem.
`src/controlnet_aux/mesh_graphormer/pipeline.py`
```python
with open(str( Path(__file__).parent / "hand_landmarker.task" ), 'rb') as file:
   model_data = file.read()
base_options = python.BaseOptions(model_asset_buffer=model_data)
```

**Comment by DivinoAG** [comment]
I can confirm that the solution above works as well. However, if like me you're a bit confused as to where you need to change that, specifically it's on the file above, line 194, replace the single line:

```python
base_options = python.BaseOptions(model_asset_path=str( Path(__file__).parent / "hand_landmarker.task" ))
``` 

... with the three lines above. Took me a hot minute to find it, so I thought someone else might also need an assistance.

Thanks @PaulWolfgang for finding the solution ;)
