### ISSUE TITLE
ValueError: not allowed to raise maximum limit

### ISSUE THREAD

**Issue by kanbekotori** [Fannovel16/comfyui_controlnet_aux#211]
Running comfyui on Runpod, I get the following error:
```
2024-01-16T02:48:21.368159016Z ERROR:root:!!! Exception during processing !!!
2024-01-16T02:48:21.368828357Z ERROR:root:Traceback (most recent call last):
2024-01-16T02:48:21.368844053Z   File "/comfyui/execution.py", line 154, in recursive_execute
2024-01-16T02:48:21.368848987Z     output_data, output_ui = get_output_data(obj, input_data_all)
2024-01-16T02:48:21.368854260Z   File "/comfyui/execution.py", line 84, in get_output_data
2024-01-16T02:48:21.368858540Z     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
2024-01-16T02:48:21.368863367Z   File "/comfyui/execution.py", line 77, in map_node_over_list
2024-01-16T02:48:21.368867600Z     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
2024-01-16T02:48:21.368871807Z   File "/comfyui/custom_nodes/comfyui_controlnet_aux/__init__.py", line 109, in execute
2024-01-16T02:48:21.368876150Z     return getattr(aux_class(), aux_class.FUNCTION)(**params)
2024-01-16T02:48:21.368883490Z   File "/comfyui/custom_nodes/comfyui_controlnet_aux/node_wrappers/uniformer.py", line 15, in semantic_segmentate
2024-01-16T02:48:21.368888110Z     from controlnet_aux.uniformer import UniformerSegmentor
2024-01-16T02:48:21.368892370Z   File "/comfyui/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/uniformer/__init__.py", line 2, in <module>
2024-01-16T02:48:21.368896550Z     from .inference import init_segmentor, inference_segmentor, show_result_pyplot
2024-01-16T02:48:21.368900880Z   File "/comfyui/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/uniformer/inference.py", line 7, in <module>
2024-01-16T02:48:21.368905053Z     from custom_mmpkg.custom_mmseg.datasets.pipelines import Compose
2024-01-16T02:48:21.368909220Z   File "/comfyui/custom_nodes/comfyui_controlnet_aux/src/custom_mmpkg/custom_mmseg/datasets/__init__.py", line 1, in <module>
2024-01-16T02:48:21.368913460Z     from .ade import ADE20KDataset
2024-01-16T02:48:21.368917643Z   File "/comfyui/custom_nodes/comfyui_controlnet_aux/src/custom_mmpkg/custom_mmseg/datasets/ade.py", line 1, in <module>
2024-01-16T02:48:21.368921800Z     from .builder import DATASETS
2024-01-16T02:48:21.368925910Z   File "/comfyui/custom_nodes/comfyui_controlnet_aux/src/custom_mmpkg/custom_mmseg/datasets/builder.py", line 19, in <module>
2024-01-16T02:48:21.368930097Z     resource.setrlimit(resource.RLIMIT_NOFILE, (soft_limit, hard_limit))
2024-01-16T02:48:21.368934140Z ValueError: not allowed to raise maximum limit
```
I asked in the Runpod community and got the following response:
`You can't raise the limits in RunPod, you need to either disable that or contact the devel;oper of the plugin to fix it.`

Can I remove this code from comfyui\custom_nodes\comfyui_controlnet_aux\src\custom_mmpkg\custom_mmseg\datasets\builder.py?
```python
if platform.system() != 'Windows':
    # https://github.com/pytorch/pytorch/issues/973
    import resource
    rlimit = resource.getrlimit(resource.RLIMIT_NOFILE)
    hard_limit = rlimit[1]
    soft_limit = min(4096, hard_limit)
    resource.setrlimit(resource.RLIMIT_NOFILE, (soft_limit, hard_limit))
```

**Comment by Fannovel16** [comment]
The error mentioned in that part is already fixed so I guess there won't be any problem if it's removed
