### ISSUE TITLE
[Import Failed] Controlnet_Aux - Can't find previous Issues/solutions

### ISSUE THREAD

**Issue by Zlata-Salyukova** [Fannovel16/comfyui_controlnet_aux#249]
I had this error popup the other day and cannot find any fixes or previous solutions.
I tried updating Controlnet_Aux to get the "Depth Anything" node working.

Since then, even after trying the Reactor nodes suggested fix:
https://github.com/Gourieff/comfyui-reactor-node#iv-controlnet-aux-node-import-failed-error-when-using-with-reactor-node

I have updated everything I could, tried reinstalling, and anything else, the import still fails.

I am posting screenshots and logs for better context, please let me know if I need to provide any additional info. 

Thank you!
<img width="1910" alt="Controlnet aux issue 1" src="https://github.com/Fannovel16/comfyui_controlnet_aux/assets/109472299/c6768a10-e4de-416e-8a2b-607d11b8c73c">

<img width="1655" alt="Controlnet aux issue 2" src="https://github.com/Fannovel16/comfyui_controlnet_aux/assets/109472299/0642562b-1bf8-4a06-a6ba-7dbfa308f00c">

Logs:
** ComfyUI startup time: 2024-02-15 15:46:15.079089
[2024-02-15 15:46] ** Platform: Windows
[2024-02-15 15:46] ** Python version: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
[2024-02-15 15:46] ** Python executable: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe
[2024-02-15 15:46] ** Log path: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\comfyui.log
[2024-02-15 15:46] 
Prestartup times for custom nodes:
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-02-15 15:46] 
[2024-02-15 15:46] Total VRAM 8192 MB, total RAM 32459 MB
[2024-02-15 15:46] xformers version: 0.0.24+cu118
[2024-02-15 15:46] Set vram state to: NORMAL_VRAM
[2024-02-15 15:46] Device: cuda:0 NVIDIA GeForce RTX 3080 Laptop GPU : cudaMallocAsync
[2024-02-15 15:46] VAE dtype: torch.bfloat16
[2024-02-15 15:46] Using xformers cross attention
[2024-02-15 15:46] My Custom Nodes Loaded
[2024-02-15 15:46] [92mBmad-DirtyUndoRedo Loaded.[0m
[2024-02-15 15:46] Skip C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Bmad-DirtyUndoRedo module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.
[2024-02-15 15:46] ### Loading: ComfyUI-Impact-Pack (V4.70)
[2024-02-15 15:46] ### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
[2024-02-15 15:46] ### Loading: ComfyUI-Inspire-Pack (V0.61.5)
[2024-02-15 15:46] [Impact Pack] Wildcards loading done.
[2024-02-15 15:46] ### Loading: ComfyUI-Manager (V2.4.2)
[2024-02-15 15:46] ### ComfyUI Revision: 1973 [7f89cb48] | Released on '2024-02-14'
[2024-02-15 15:46] packaging is already installed.
[2024-02-15 15:46] cpuinfo is already installed.
[2024-02-15 15:46] git is already installed.
[2024-02-15 15:46] moviepy is already installed.
[2024-02-15 15:46] cv2 is already installed.
[2024-02-15 15:46] skbuild is already installed.
[2024-02-15 15:46] typing is already installed.
[2024-02-15 15:46] diskcache is already installed.
[2024-02-15 15:46] llama_cpp is already installed.
[2024-02-15 15:46] 
[2024-02-15 15:46] [34mOpenPose Editor: [92mLoaded[0m
[2024-02-15 15:46] Traceback (most recent call last):
  File "C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-reader-node\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-reader-node\nodes.py", line 31, in <module>
    from .stable_diffusion_prompt_reader.sd_prompt_reader.constants import (
ModuleNotFoundError: No module named 'comfyui-prompt-reader-node.stable_diffusion_prompt_reader.sd_prompt_reader'
[2024-02-15 15:46] 
[2024-02-15 15:46] Cannot import C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-reader-node module for custom nodes: No module named 'comfyui-prompt-reader-node.stable_diffusion_prompt_reader.sd_prompt_reader'
[2024-02-15 15:46] Total VRAM 8192 MB, total RAM 32459 MB
[2024-02-15 15:46] xformers version: 0.0.24+cu118
[2024-02-15 15:46] Set vram state to: NORMAL_VRAM
[2024-02-15 15:46] Device: cuda:0 NVIDIA GeForce RTX 3080 Laptop GPU : cudaMallocAsync
[2024-02-15 15:46] VAE dtype: torch.bfloat16
[2024-02-15 15:46] [0;33m[ReActor][0m - [38;5;173mSTATUS[0m - [0;32mRunning v0.4.1-b9 in ComfyUI[0m
[2024-02-15 15:46] Torch version: 2.2.0+cu118
[2024-02-15 15:46] [VideoHelperSuite] - [0;32mINFO[0m - ffmpeg could not be found. Using ffmpeg from imageio-ffmpeg.
[2024-02-15 15:46] ------------------------------------------
[2024-02-15 15:46] [34mComfyroll Studio v1.76 : [92m 175 Nodes Loaded[0m
[2024-02-15 15:46] ------------------------------------------
[2024-02-15 15:46] ** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
[2024-02-15 15:46] ** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
[2024-02-15 15:46] ------------------------------------------
[2024-02-15 15:46] Traceback (most recent call last):
  File "C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 2, in <module>
    from .utils import here, create_node_input_types
ModuleNotFoundError: No module named 'comfyui_controlnet_aux.utils'
[2024-02-15 15:46] 
[2024-02-15 15:46] Cannot import C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux module for custom nodes: No module named 'comfyui_controlnet_aux.utils'
[2024-02-15 15:46] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[2024-02-15 15:46] [34mFizzleDorf Custom Nodes: [92mLoaded[0m
[2024-02-15 15:46] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[2024-02-15 15:46] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2024-02-15 15:46] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[2024-02-15 15:46] [92m[tinyterraNodes] [32mLoaded[0m
[2024-02-15 15:46] 
[36mEfficiency Nodes:[0m Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...[91mFailed![0m
[2024-02-15 15:46] [36mEfficiency Nodes:[0m Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...
[36mEfficiency Nodes:[0m Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...[91mFailed![0m
[2024-02-15 15:46] Total VRAM 8192 MB, total RAM 32459 MB
[2024-02-15 15:46] xformers version: 0.0.24+cu118
[2024-02-15 15:46] Set vram state to: NORMAL_VRAM
[2024-02-15 15:46] Device: cuda:0 NVIDIA GeForce RTX 3080 Laptop GPU : cudaMallocAsync
[2024-02-15 15:46] VAE dtype: torch.bfloat16
[2024-02-15 15:46] Traceback (most recent call last):
  File "C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\prose\\Documents\\UnstableDiffusion\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\IPAdapter-ComfyUI\\__init__.py'
[2024-02-15 15:46] 
[2024-02-15 15:46] Cannot import C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\prose\\Documents\\UnstableDiffusion\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\IPAdapter-ComfyUI\\__init__.py'
[2024-02-15 15:46] Searge-SDXL v4.3.1 in C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
[2024-02-15 15:46] [34mWAS Node Suite: [0mOpenCV Python FFMPEG support is enabled[0m
[2024-02-15 15:46] [34mWAS Node Suite [93mWarning: [0m`ffmpeg_bin_path` is not set in `C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.[0m
[2024-02-15 15:46] [34mWAS Node Suite: [0mFinished.[0m [32mLoaded[0m [0m211[0m [32mnodes successfully.[0m
[2024-02-15 15:46] 
	[3m[93m"Every artist was first an amateur."[0m[3m - Ralph Waldo Emerson[0m
[2024-02-15 15:46] 
[2024-02-15 15:46] 
Import times for custom nodes:
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\canvas_tab
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl-recommended-res-calc
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_toyxyz_test_nodes
[2024-02-15 15:46]    0.0 seconds (IMPORT FAILED): C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Bmad-DirtyUndoRedo
[2024-02-15 15:46]    0.0 seconds (IMPORT FAILED): C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
[2024-02-15 15:46]    0.0 seconds (IMPORT FAILED): C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Batch_Mask
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUi_PromptStylers
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-tooling-nodes
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_NestedNodeBuilder
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OpenPose-Editor-master
[2024-02-15 15:46]    0.0 seconds (IMPORT FAILED): C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-reader-node
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\mikey_nodes
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite - Fix
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf
[2024-02-15 15:46]    0.0 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
[2024-02-15 15:46]    0.2 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
[2024-02-15 15:46]    0.2 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
[2024-02-15 15:46]    0.2 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
[2024-02-15 15:46]    0.3 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_Mile_High_prompt_styler-main
[2024-02-15 15:46]    0.3 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
[2024-02-15 15:46]    0.3 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes
[2024-02-15 15:46]    0.4 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-02-15 15:46]    0.6 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
[2024-02-15 15:46]    0.8 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[2024-02-15 15:46]    1.2 seconds: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
[2024-02-15 15:46] 
[2024-02-15 15:46] Starting server
[2024-02-15 15:46] 
[2024-02-15 15:46] To see the GUI go to: http://127.0.0.1:8188
[2024-02-15 15:46] FETCH DATA from: C:\Users\prose\Documents\UnstableDiffusion\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
[2024-02-15 15:56] FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2024-02-15 15:56] FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[2024-02-15 15:56] FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json

**Comment by Layer-norm** [comment]
These error below is strange，because there isn't any function named `call_with_frames_removed` in comfyui controlnet aux
```
File "", line 883, in exec_module
File "", line 241, in call_with_frames_removed
```
Is there some hidden items except `.git` (folder or file, e.g. `.ipynb_checkpoints`) in your folders? If so, remove them.
