### ISSUE TITLE
Error in importing dwpose.py

### ISSUE THREAD

**Issue by amnesicloud** [Fannovel16/comfyui_controlnet_aux#250]
Hi, I'm encountering problem when trying to import dwpose.py. It looks like the problem is cuda version or torch version, I'm wondering that is there specific requirements for cuda or pytorch version?

currently I'm using cuda version 11.7, torch version 1.13.1, python version 3.10.13

Full error log from comfyui_controlnet_aux: 
Traceback (most recent call last):
  File "/home/yunz/ComfyUI/custom_nodes/comfyui_controlnet_aux/__init__.py", line 32, in load_nodes
    module = importlib.import_module(
  File "/root/anaconda3/envs/yunz/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/yunz/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py", line 5, in <module>
    from controlnet_aux.dwpose import DwposeDetector, AnimalposeDetector
  File "/home/yunz/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/dwpose/__init__.py", line 9, in <module>
    benchmark.timer()
  File "/root/anaconda3/envs/yunz/lib/python3.10/site-packages/torch/utils/benchmark/utils/timer.py", line 18, in timer
    torch.cuda.synchronize()
  File "/root/anaconda3/envs/yunz/lib/python3.10/site-packages/torch/cuda/__init__.py", line 566, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: device kernel image is invalid
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

full comfyui.log is as follow:

** ComfyUI startup time: 2024-02-17 09:49:49.097781
[2024-02-17 09:49] ** Platform: Linux
[2024-02-17 09:49] ** Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
[2024-02-17 09:49] ** Python executable: /root/anaconda3/envs/yunz/bin/python
[2024-02-17 09:49] ** Log path: /home/yunz/ComfyUI/comfyui.log
[2024-02-17 09:49] 
Prestartup times for custom nodes:
[2024-02-17 09:49]    0.0 seconds: /home/yunz/ComfyUI/custom_nodes/rgthree-comfy
[2024-02-17 09:49]    0.0 seconds: /home/yunz/ComfyUI/custom_nodes/ComfyUI-Manager
[2024-02-17 09:49] 
[2024-02-17 09:49] Total VRAM 15110 MB, total RAM 515129 MB
[2024-02-17 09:49] Set vram state to: NORMAL_VRAM
[2024-02-17 09:49] Device: cuda:0 Tesla T4 : 
[2024-02-17 09:49] VAE dtype: torch.float32
[2024-02-17 09:49] Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
[2024-02-17 09:49] Total VRAM 0 MB, total RAM 515129 MB
[2024-02-17 09:49] Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram
[2024-02-17 09:49] Set vram state to: LOW_VRAM
[2024-02-17 09:49] Device: cuda:0 Tesla T4 : 
[2024-02-17 09:49] VAE dtype: torch.float32
[36;20m[comfy_mtb] | INFO -> loaded [96m58[0m nodes successfuly[0m
[2024-02-17 09:49] [36;20m[comfy_mtb] | INFO -> Some nodes (7) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.[0m
[2024-02-17 09:49] Traceback (most recent call last):
  File "/home/yunz/ComfyUI/nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/yunz/ComfyUI/custom_nodes/efficiency-nodes-comfyui/__init__.py", line 1, in <module>
    from .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "/home/yunz/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 46, in <module>
    from .py import smZ_cfg_denoiser
  File "/home/yunz/ComfyUI/custom_nodes/efficiency-nodes-comfyui/py/smZ_cfg_denoiser.py", line 7, in <module>
    from comfy.samplers import KSampler, CompVisVDenoiser, KSamplerX0Inpaint
ImportError: cannot import name 'CompVisVDenoiser' from 'comfy.samplers' (/home/yunz/ComfyUI/comfy/samplers.py)
[2024-02-17 09:49] 
[2024-02-17 09:49] Cannot import /home/yunz/ComfyUI/custom_nodes/efficiency-nodes-comfyui module for custom nodes: cannot import name 'CompVisVDenoiser' from 'comfy.samplers' (/home/yunz/ComfyUI/comfy/samplers.py)
[2024-02-17 09:49] Searge-SDXL v4.3.1 in /home/yunz/ComfyUI/custom_nodes/SeargeSDXL
[2024-02-17 09:49] ### Loading: ComfyUI-Inspire-Pack (V0.64)
[2024-02-17 09:49] ### Loading: ComfyUI-Manager (V2.7.2)
[2024-02-17 09:49] ### ComfyUI Revision: 1973 [7f89cb48] | Released on '2024-02-14'
[2024-02-17 09:49] Traceback (most recent call last):
  File "/home/yunz/ComfyUI/nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/yunz/ComfyUI/custom_nodes/ComfyUI_essentials/__init__.py", line 1, in <module>
    from .essentials import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/yunz/ComfyUI/custom_nodes/ComfyUI_essentials/essentials.py", line 14, in <module>
    import torchvision.transforms.v2 as T
ModuleNotFoundError: No module named 'torchvision.transforms.v2'
[2024-02-17 09:49] 
[2024-02-17 09:49] Cannot import /home/yunz/ComfyUI/custom_nodes/ComfyUI_essentials module for custom nodes: No module named 'torchvision.transforms.v2'
[2024-02-17 09:49] [92m[tinyterraNodes] [32mLoaded[0m
[2024-02-17 09:49] [0;33m[ReActor][0m - [38;5;173mSTATUS[0m - [0;32mRunning v0.4.1-b9 in ComfyUI[0m
[2024-02-17 09:49] Torch version: 1.13.1
[2024-02-17 09:49] ------------------------------------------
[2024-02-17 09:49] [34mComfyroll Studio v1.76 : [92m 175 Nodes Loaded[0m
[2024-02-17 09:49] ------------------------------------------
[2024-02-17 09:49] ** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
[2024-02-17 09:49] ** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
[2024-02-17 09:49] ------------------------------------------
[2024-02-17 09:49] [34mFizzleDorf Custom Nodes: [92mLoaded[0m
[2024-02-17 09:49] Traceback (most recent call last):
  File "/root/anaconda3/envs/yunz/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1110, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/root/anaconda3/envs/yunz/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/anaconda3/envs/yunz/lib/python3.10/site-packages/transformers/models/clipseg/modeling_clipseg.py", line 28, in <module>
    from ...modeling_utils import PreTrainedModel
  File "/root/anaconda3/envs/yunz/lib/python3.10/site-packages/transformers/modeling_utils.py", line 83, in <module>
    from accelerate import __version__ as accelerate_version
  File "/root/anaconda3/envs/yunz/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/root/anaconda3/envs/yunz/lib/python3.10/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/root/anaconda3/envs/yunz/lib/python3.10/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/root/anaconda3/envs/yunz/lib/python3.10/site-packages/accelerate/utils/__init__.py", line 158, in <module>
    from .fsdp_utils import load_fsdp_model, load_fsdp_optimizer, save_fsdp_model, save_fsdp_optimizer
  File "/root/anaconda3/envs/yunz/lib/python3.10/site-packages/accelerate/utils/fsdp_utils.py", line 27, in <module>
    from torch.distributed.checkpoint.default_planner import DefaultLoadPlanner, DefaultSavePlanner
ModuleNotFoundError: No module named 'torch.distributed.checkpoint.default_planner'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yunz/ComfyUI/nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/yunz/ComfyUI/custom_nodes/ComfyUI-KJNodes/__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/yunz/ComfyUI/custom_nodes/ComfyUI-KJNodes/nodes.py", line 2159, in <module>
    from transformers import CLIPSegProcessor, CLIPSegForImageSegmentation
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/root/anaconda3/envs/yunz/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1101, in __getattr__
    value = getattr(module, name)
  File "/root/anaconda3/envs/yunz/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1100, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/root/anaconda3/envs/yunz/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1112, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clipseg.modeling_clipseg because of the following error (look up to see its traceback):
No module named 'torch.distributed.checkpoint.default_planner'
[2024-02-17 09:49] 
[2024-02-17 09:49] Cannot import /home/yunz/ComfyUI/custom_nodes/ComfyUI-KJNodes module for custom nodes: Failed to import transformers.models.clipseg.modeling_clipseg because of the following error (look up to see its traceback):
No module named 'torch.distributed.checkpoint.default_planner'
[2024-02-17 09:49] ### Loading: ComfyUI-Impact-Pack (V4.76.1)
[2024-02-17 09:49] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[2024-02-17 09:49] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[2024-02-17 09:49] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[2024-02-17 09:49] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2024-02-17 09:50] ### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
[2024-02-17 09:50] [Impact Pack] Wildcards loading done.
[2024-02-17 09:50] 
[2024-02-17 09:50] [92m[rgthree] Loaded 33 fantastic nodes.[0m
[2024-02-17 09:50] [92m[rgthree] Will use rgthree's optimized recursive execution.[0m
[2024-02-17 09:50] 
[2024-02-17 09:50] [34mWAS Node Suite: [0mBlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.[0m
[2024-02-17 09:50] [34mWAS Node Suite: [0m`CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.[0m
[2024-02-17 09:50] [34mWAS Node Suite: [0mOpenCV Python FFMPEG support is enabled[0m
[2024-02-17 09:50] [34mWAS Node Suite [93mWarning: [0m`ffmpeg_bin_path` is not set in `/home/yunz/ComfyUI/custom_nodes/was-node-suite-comfyui/was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.[0m
[2024-02-17 09:50] [34mWAS Node Suite: [0mFinished.[0m [32mLoaded[0m [0m212[0m [32mnodes successfully.[0m
[2024-02-17 09:50] 
	[3m[93m"Art is the lie that enables us to realize the truth."[0m[3m - Pablo Picasso[0m
[2024-02-17 09:50] 
[2024-02-17 09:50] Skip /home/yunz/ComfyUI/custom_nodes/__init__.py module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.
[2024-02-17 09:50] ====================================================================================================
[2024-02-17 09:50] /home/yunz/ComfyUI/custom_nodes/comfyui_controlnet_aux
[2024-02-17 09:50] [36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: /home/yunz/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts[0m
[2024-02-17 09:50] [36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
[2024-02-17 09:50] [36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
[2024-02-17 09:50] 

Full error log from comfyui_controlnet_aux: 
Traceback (most recent call last):
  File "/home/yunz/ComfyUI/custom_nodes/comfyui_controlnet_aux/__init__.py", line 32, in load_nodes
    module = importlib.import_module(
  File "/root/anaconda3/envs/yunz/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/yunz/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py", line 5, in <module>
    from controlnet_aux.dwpose import DwposeDetector, AnimalposeDetector
  File "/home/yunz/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/dwpose/__init__.py", line 9, in <module>
    benchmark.timer()
  File "/root/anaconda3/envs/yunz/lib/python3.10/site-packages/torch/utils/benchmark/utils/timer.py", line 18, in timer
    torch.cuda.synchronize()
  File "/root/anaconda3/envs/yunz/lib/python3.10/site-packages/torch/cuda/__init__.py", line 566, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: device kernel image is invalid
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

[2024-02-17 09:50] 
[2024-02-17 09:50] [36;20m[comfyui_controlnet_aux] | INFO -> Some nodes failed to load:
	Failed to import module dwpose because For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/Fannovel16/comfyui_controlnet_aux/issues)[0m
[2024-02-17 09:50] ####################################################################################################
[2024-02-17 09:50] /home/yunz/ComfyUI/custom_nodes/comfyui_controlnet_aux
[2024-02-17 09:50] True
[2024-02-17 09:50] {'AnimeFace_SemSegPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.anime_face_segment.AnimeFace_SemSegPreprocessor'>, 'BinaryPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.binary.Binary_Preprocessor'>, 'CannyEdgePreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.canny.Canny_Edge_Preprocessor'>, 'ColorPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.color.Color_Preprocessor'>, 'DensePosePreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.densepose.DensePose_Preprocessor'>, 'DepthAnythingPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.depth_anything.Depth_Anything_Preprocessor'>, 'Zoe_DepthAnythingPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.depth_anything.Zoe_Depth_Anything_Preprocessor'>, 'DiffusionEdge_Preprocessor': <class 'comfyui_controlnet_aux.node_wrappers.diffusion_edge.DiffusionEdge_Preprocessor'>, 'HEDPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.hed.HED_Preprocessor'>, 'FakeScribblePreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.hed.Fake_Scribble_Preprocessor'>, 'InpaintPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.inpaint.InpaintPreprocessor'>, 'LeReS-DepthMapPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.leres.LERES_Depth_Map_Preprocessor'>, 'LineArtPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.lineart.LineArt_Preprocessor'>, 'AnimeLineArtPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.lineart_anime.AnimeLineArt_Preprocessor'>, 'LineartStandardPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.lineart_standard.Lineart_Standard_Preprocessor'>, 'Manga2Anime_LineArt_Preprocessor': <class 'comfyui_controlnet_aux.node_wrappers.manga_line.Manga2Anime_LineArt_Preprocessor'>, 'MediaPipe-FaceMeshPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.mediapipe_face.Media_Pipe_Face_Mesh_Preprocessor'>, 'MeshGraphormer-DepthMapPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.mesh_graphormer.Mesh_Graphormer_Depth_Map_Preprocessor'>, 'MiDaS-NormalMapPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.midas.MIDAS_Normal_Map_Preprocessor'>, 'MiDaS-DepthMapPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.midas.MIDAS_Depth_Map_Preprocessor'>, 'M-LSDPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.mlsd.MLSD_Preprocessor'>, 'BAE-NormalMapPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.normalbae.BAE_Normal_Map_Preprocessor'>, 'OneFormer-COCO-SemSegPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.oneformer.OneFormer_COCO_SemSegPreprocessor'>, 'OneFormer-ADE20K-SemSegPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.oneformer.OneFormer_ADE20K_SemSegPreprocessor'>, 'OpenposePreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.openpose.OpenPose_Preprocessor'>, 'PiDiNetPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.pidinet.PIDINET_Preprocessor'>, 'SavePoseKpsAsJsonFile': <class 'comfyui_controlnet_aux.node_wrappers.pose_keypoint_postprocess.SavePoseKpsAsJsonFile'>, 'FacialPartColoringFromPoseKps': <class 'comfyui_controlnet_aux.node_wrappers.pose_keypoint_postprocess.FacialPartColoringFromPoseKps'>, 'ImageLuminanceDetector': <class 'comfyui_controlnet_aux.node_wrappers.recolor.ImageLuminanceDetector'>, 'ImageIntensityDetector': <class 'comfyui_controlnet_aux.node_wrappers.recolor.ImageIntensityDetector'>, 'ScribblePreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.scribble.Scribble_Preprocessor'>, 'Scribble_XDoG_Preprocessor': <class 'comfyui_controlnet_aux.node_wrappers.scribble.Scribble_XDoG_Preprocessor'>, 'SAMPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.segment_anything.SAM_Preprocessor'>, 'ShufflePreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.shuffle.Shuffle_Preprocessor'>, 'TEEDPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.teed.TEED_Preprocessor'>, 'TilePreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.tile.Tile_Preprocessor'>, 'UniFormer-SemSegPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.uniformer.Uniformer_SemSegPreprocessor'>, 'SemSegPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.uniformer.Uniformer_SemSegPreprocessor'>, 'Unimatch_OptFlowPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.unimatch.Unimatch_OptFlowPreprocessor'>, 'MaskOptFlow': <class 'comfyui_controlnet_aux.node_wrappers.unimatch.MaskOptFlow'>, 'Zoe-DepthMapPreprocessor': <class 'comfyui_controlnet_aux.node_wrappers.zoe.Zoe_Depth_Map_Preprocessor'>, 'AIO_Preprocessor': <class 'comfyui_controlnet_aux.AIO_Preprocessor'>, 'PixelPerfectResolution': <class 'comfyui_controlnet_aux.hint_image_enchance.PixelPerfectResolution'>, 'ImageGenResolutionFromImage': <class 'comfyui_controlnet_aux.hint_image_enchance.ImageGenResolutionFromImage'>, 'ImageGenResolutionFromLatent': <class 'comfyui_controlnet_aux.hint_image_enchance.ImageGenResolutionFromLatent'>, 'HintImageEnchance': <class 'comfyui_controlnet_aux.hint_image_enchance.HintImageEnchance'>}
[2024-02-17 09:50] 
Import times for custom nodes:
[2024-02-17 09:50]    0.0 seconds (IMPORT FAILED): /home/yunz/ComfyUI/custom_nodes/__init__.py
[2024-02-17 09:50]    0.0 seconds: /home/yunz/ComfyUI/custom_nodes/sdxl_prompt_styler
[2024-02-17 09:50]    0.0 seconds: /home/yunz/ComfyUI/custom_nodes/cg-use-everywhere
[2024-02-17 09:50]    0.0 seconds: /home/yunz/ComfyUI/custom_nodes/ComfyUI_ADV_CLIP_emb
[2024-02-17 09:50]    0.0 seconds: /home/yunz/ComfyUI/custom_nodes/stability-ComfyUI-nodes
[2024-02-17 09:50]    0.0 seconds: /home/yunz/ComfyUI/custom_nodes/ComfyUI-WD14-Tagger
[2024-02-17 09:50]    0.0 seconds: /home/yunz/ComfyUI/custom_nodes/comfyui-yanc
[2024-02-17 09:50]    0.0 seconds: /home/yunz/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
[2024-02-17 09:50]    0.0 seconds: /home/yunz/ComfyUI/custom_nodes/ComfyUI_FizzNodes
[2024-02-17 09:50]    0.0 seconds: /home/yunz/ComfyUI/custom_nodes/wlsh_nodes
[2024-02-17 09:50]    0.0 seconds: /home/yunz/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
[2024-02-17 09:50]    0.0 seconds: /home/yunz/ComfyUI/custom_nodes/Derfuu_ComfyUI_ModdedNodes
[2024-02-17 09:50]    0.0 seconds: /home/yunz/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
[2024-02-17 09:50]    0.0 seconds: /home/yunz/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation
[2024-02-17 09:50]    0.0 seconds (IMPORT FAILED): /home/yunz/ComfyUI/custom_nodes/efficiency-nodes-comfyui
[2024-02-17 09:50]    0.0 seconds: /home/yunz/ComfyUI/custom_nodes/rgthree-comfy
[2024-02-17 09:50]    0.0 seconds: /home/yunz/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
[2024-02-17 09:50]    0.0 seconds (IMPORT FAILED): /home/yunz/ComfyUI/custom_nodes/ComfyUI_essentials
[2024-02-17 09:50]    0.0 seconds: /home/yunz/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes
[2024-02-17 09:50]    0.0 seconds: /home/yunz/ComfyUI/custom_nodes/comfyui-reactor-node
[2024-02-17 09:50]    0.0 seconds: /home/yunz/ComfyUI/custom_nodes/ComfyUI-Manager
[2024-02-17 09:50]    0.0 seconds: /home/yunz/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
[2024-02-17 09:50]    0.1 seconds: /home/yunz/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
[2024-02-17 09:50]    0.1 seconds (IMPORT FAILED): /home/yunz/ComfyUI/custom_nodes/ComfyUI-KJNodes
[2024-02-17 09:50]    0.1 seconds: /home/yunz/ComfyUI/custom_nodes/facerestore_cf
[2024-02-17 09:50]    0.2 seconds: /home/yunz/ComfyUI/custom_nodes/bilbox-comfyui
[2024-02-17 09:50]    0.3 seconds: /home/yunz/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
[2024-02-17 09:50]    0.3 seconds: /home/yunz/ComfyUI/custom_nodes/comfyui_controlnet_aux
[2024-02-17 09:50]    0.3 seconds: /home/yunz/ComfyUI/custom_nodes/SeargeSDXL
[2024-02-17 09:50]    0.6 seconds: /home/yunz/ComfyUI/custom_nodes/comfy_controlnet_preprocessors
[2024-02-17 09:50]    0.9 seconds: /home/yunz/ComfyUI/custom_nodes/was-node-suite-comfyui
[2024-02-17 09:50]    1.5 seconds: /home/yunz/ComfyUI/custom_nodes/comfy_mtb
[2024-02-17 09:50]    6.1 seconds: /home/yunz/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
[2024-02-17 09:50] 
[2024-02-17 09:50] Starting server
[2024-02-17 09:50] 
[2024-02-17 09:50] To see the GUI go to: http://127.0.0.1:8188
[2024-02-17 09:50] 
Stopped server

**Comment by Layer-norm** [comment]
It is suggested that cuda version is higher than 11.8,  but other version should work too if the environment built properly.

It seems that you update some packages such as **diffusion** and **transformers**, but your pytorch and cuda not, because `torch.distributed.checkpoint.default_planner`  is only in torch 2.2.0 and  `torchvision.transforms.v2` in torchvison after 0.15. 

Maybe you need to build a new python environment for comfyui with the latest cuda and pytorch version.
`
