### ISSUE TITLE
Error occurred when executing Oneformer Coco Segmentor

### ISSUE THREAD

**Issue by feidexiang** [Fannovel16/comfyui_controlnet_aux#251]
python 3.10.13
torch: 2.1.2
matplotlib 3.8.3

Error occurred when executing Oneformer Coco Segmentor:

ERROR:root:Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/ubuntu/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/ubuntu/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/oneformer.py", line 38, in semantic_segmentate
    out = common_annotator_call(model, image, resolution=resolution)
  File "/home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux/utils.py", line 67, in common_annotator_call
    np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)
  File "/home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/oneformer/__init__.py", line 42, in __call__
    detected_map = semantic_run(input_image, self.model, self.metadata)
  File "/home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/oneformer/api.py", line 37, in semantic_run
    visualizer_map = Visualizer(img, is_img=False, metadata=metadata, instance_mode=ColorMode.IMAGE)
  File "/home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_oneformer/demo/visualizer.py", line 383, in __init__
    self.output = VisImage(self.img, scale=scale)
  File "/home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_oneformer/demo/visualizer.py", line 279, in __init__
    self._setup_figure(img)
  File "/home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_oneformer/demo/visualizer.py", line 299, in _setup_figure
    ax = fig.add_axes([0.0, 0.0, 1.0, 1.0])
  File "/home/ubuntu/anaconda3/envs/sd/lib/python3.10/site-packages/matplotlib/figure.py", line 648, in add_axes
    a = projection_class(self, rect, **pkw)
  File "/home/ubuntu/anaconda3/envs/sd/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 670, in __init__
    self._init_axis()
  File "/home/ubuntu/anaconda3/envs/sd/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 812, in _init_axis
    self.xaxis = maxis.XAxis(self, clear=False)
  File "/home/ubuntu/anaconda3/envs/sd/lib/python3.10/site-packages/matplotlib/axis.py", line 2295, in __init__
    super().__init__(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/sd/lib/python3.10/site-packages/matplotlib/axis.py", line 676, in __init__
    self.label = mtext.Text(
  File "/home/ubuntu/anaconda3/envs/sd/lib/python3.10/site-packages/matplotlib/text.py", line 155, in __init__
    self.update(kwargs)
  File "/home/ubuntu/anaconda3/envs/sd/lib/python3.10/site-packages/matplotlib/text.py", line 197, in update
    kwargs = cbook.normalize_kwargs(kwargs, Text)
  File "/home/ubuntu/anaconda3/envs/sd/lib/python3.10/site-packages/matplotlib/cbook.py", line 1783, in normalize_kwargs
    for canonical, alias_list in alias_mapping.items()
AttributeError: type object 'Text' has no attribute 'items'

**Comment by wibur0620** [comment]
I'm experiencing the exact same error as you, have you solved the error now?

**Comment by brgrp** [comment]
Same here!

**Comment by TheNewon** [comment]
I'm experiencing the same problem. I suspect it might be related to the matplotlib version. Unfortunately, I can't install a version lower than 3.6.0 with Python 3.11. You might want to try downgrading Python to 3.6 or another older version and then install matplotlib 2.2.5 to see if this resolves the issue.

**Comment by TheNewon** [comment]
Ok i found how to fix it. (important to use python 3.9 as it is minimal suported version for confyui)
 Install miniconda3.
 add it to Path.
 conda create --name confyui python==3.9 
 conda init
 conda activate confyui
 conda install -n confyui  conda-forge::matplotlib
 go to ComfyUI_windows_portable folder
 python -s -m pip install --upgrade -r ./ComfyUI/requirements.txt pygit2
 python -s -m pip install --upgrade torch torchvision torchaudio  --extra-index-url https://download.pytorch.org/whl/cu121
 python  -m pip install librosa anthropic deepdiff chromadb opencv-python fvcore pypiwin32 omegaconf ftfy

make bat script named run_localy.bat
call conda activate confyui
python -s ComfyUI\main.py --windows-standalone-build
pause

inside ComfyUI go to manager and fix custom nodes if needed.
