### ISSUE TITLE
Mask optical flow (DragNuwa) doesn't work

### ISSUE THREAD

**Issue by Cedri4** [Fannovel16/comfyui_controlnet_aux#296]
Hi, I keep having an issue when I try using the flow from the comfyui-optical-flow custom node (https://github.com/seanlynch/comfyui-optical-flow) and a mask.
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/93396286/6b69ed7b-ad58-4e04-8c69-838bdf6f0108)

I checked if the mask and the image input for the flow are the same size. And they are.
The error on the terminal.

torch.Size([1, 512, 912, 3]) tensor(1.) <class 'torch.Tensor'>
torch.Size([512, 912, 3]) torch.Size([912, 512, 2])
0.102892 (1276, 876, 2) float32
!!! Exception during processing !!!
Traceback (most recent call last):
  File "F:\Stable-Diffusion\ComfyUI\WorkComfy\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable-Diffusion\ComfyUI\WorkComfy\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable-Diffusion\ComfyUI\WorkComfy\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 381, in new_func
    res_value = old_func(*final_args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable-Diffusion\ComfyUI\WorkComfy\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable-Diffusion\ComfyUI\WorkComfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\unimatch.py", line 59, in mask_opt_flow
    mask = mask[:optical_flow.shape[0]]
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'shape'

**Comment by Layer-norm** [comment]
Oh, it just coincidentally uses the same value name, optical_flow. There is no connection between these two repos. 
Besides, you should use images instead of a single image because optical flow is used to calculate the difference between two frames.
![optical_flow](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/140777998/dffb9823-08ff-4c37-a26a-ea6600763b3e)
You can find more details from[ComfyUI-DragNUWA](https://github.com/chaojie/ComfyUI-DragNUWA)
