### ISSUE TITLE
Meet error when use DWPreprocessor "assert '_distutils' in core.__file__, core.__file__"

### ISSUE THREAD

**Issue by 6174** [Fannovel16/comfyui_controlnet_aux#299]
The full Error is below:

```
DWPose: Using yolox_l.onnx for bbox detection and dw-ll_ucoco.onnx for pose estimation
DWPose: Caching ONNXRuntime session yolox_l.onnx...
DWPose: Caching ONNXRuntime session dw-ll_ucoco.onnx...
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/Users/chenxuejia/comflowy/CmofyUI2/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/Users/chenxuejia/comflowy/CmofyUI2/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/Users/chenxuejia/comflowy/CmofyUI2/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/Users/chenxuejia/comflowy/CmofyUI2/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py", line 87, in estimate_pose
    out = common_annotator_call(func, image, include_hand=detect_hand, include_face=detect_face, include_body=detect_body, image_and_json=True, resolution=resolution)
  File "/Users/chenxuejia/comflowy/CmofyUI2/custom_nodes/comfyui_controlnet_aux/utils.py", line 82, in common_annotator_call
    np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)
  File "/Users/chenxuejia/comflowy/CmofyUI2/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py", line 83, in func
    pose_img, openpose_dict = model(image, **kwargs)
  File "/Users/chenxuejia/comflowy/CmofyUI2/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/dwpose/__init__.py", line 199, in __call__
    poses = self.detect_poses(input_image)
  File "/Users/chenxuejia/comflowy/CmofyUI2/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/dwpose/__init__.py", line 187, in detect_poses
    keypoints_info = self.dw_pose_estimation(oriImg.copy())
  File "/Users/chenxuejia/comflowy/CmofyUI2/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/dwpose/wholebody.py", line 80, in __call__
    import torch.utils.benchmark.utils.timer as torch_timer
  File "/Users/chenxuejia/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/utils/benchmark/__init__.py", line 2, in <module>
    from torch.utils.benchmark.utils.timer import *  # noqa: F403
  File "/Users/chenxuejia/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/utils/benchmark/utils/timer.py", line 8, in <module>
    from torch.utils.benchmark.utils import common, cpp_jit
  File "/Users/chenxuejia/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/utils/benchmark/utils/cpp_jit.py", line 13, in <module>
    from torch.utils import cpp_extension
  File "/Users/chenxuejia/miniconda3/envs/comflowy/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 9, in <module>
    import setuptools
  File "/Users/chenxuejia/miniconda3/envs/comflowy/lib/python3.10/site-packages/setuptools/__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "/Users/chenxuejia/miniconda3/envs/comflowy/lib/python3.10/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/Users/chenxuejia/miniconda3/envs/comflowy/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 70, in do_override
    ensure_local_distutils()
  File "/Users/chenxuejia/miniconda3/envs/comflowy/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 57, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: /Users/chenxuejia/miniconda3/envs/comflowy/lib/python3.10/distutils/core.py
```

**Comment by lht-ryu** [comment]
Try downgrading to:
`pip install setuptools==59.8.0`
