### ISSUE TITLE
No module named 'controlnet_aux.dsine'

### ISSUE THREAD

**Issue by lognat0704** [Fannovel16/comfyui_controlnet_aux#307]
Hi,  I am tyring to get Dsine NormalMap but can import modul named No module named 'controlnet_aux.dsine'. I tried to update the package via manager on ComfyUI and it still doesnt work.

Platform: Linux, install the packge by ComfyUI manager.

`Traceback (most recent call last):
  File "/home/nelson/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nelson/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nelson/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nelson/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dsine.py", line 18, in execute
    from controlnet_aux.dsine import DsineDetector
ModuleNotFoundError: No module named 'controlnet_aux.dsine'`

**Comment by CraftBotics** [comment]
same here

**Comment by metsweet999** [comment]
same here,i guess it should because model files lacked,but, i already manually downloaded all .pth files at https://huggingface.co/lllyasviel/Annotators/tree/main ,and placed them at custom_nodes\comfyui_controlnet_aux\ckpts\lllyasviel\Annotators, restarted comfyUI ,but still didnt fixed

**Comment by osdemon** [comment]
For the same issue, are there any solutions?
