### ISSUE TITLE
MaxRetryError for requesting ZoeD_M12_N.pt or huggingface.co

### ISSUE THREAD

**Issue by YMC-GitHub** [Fannovel16/comfyui_controlnet_aux#33]
## description

when i use zoe-depth map to get image depth. sometimes it will tell me `MaxRetryError`!

## expect value:
get depth image done!

## details as below:
```
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /lllyasviel/Annotators/resolve/main/ZoeD_M12_N.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000207DC87E050>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: d6facb74-7953-4e15-a629-1ab29edfe873)')' thrown while requesting HEAD https://huggingface.co/lllyasviel/Annotators/resolve/main/ZoeD_M12_N.pt
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\code\python\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\code\python\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\code\python\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\code\python\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\zoe.py", line 18, in execute
    model = ZoeDetector.from_pretrained(HF_MODEL_NAME, cache_dir=annotator_ckpts_path).to(model_management.get_torch_device())
  File "D:\code\python\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\zoe\__init__.py", line 36, in to
    self.model.to(device)
  File "D:\code\python\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\zoe\zoedepth\models\depth_model.py", line 42, in to
    return super().to(device)
  File "D:\code\python\stable-diffusion-webui\venv-3060\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "D:\code\python\stable-diffusion-webui\venv-3060\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\code\python\stable-diffusion-webui\venv-3060\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\code\python\stable-diffusion-webui\venv-3060\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "D:\code\python\stable-diffusion-webui\venv-3060\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "D:\code\python\stable-diffusion-webui\venv-3060\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

## questions 
- how does the huggingface model save or cache in local with comfyui_controlnet_aux ? does it requset huggingface .co when 
ZoeD_M12_N.pt has been downloaded and saved to correct location ?

i have downloaded ZoeD_M12_N.pt and paste it to correct position for comfyui  `comfyui\ckpts\models--lllyasviel--Annotators\snapshots\982e7edaec38759d914a963c48c4726685de7d96\ZoeD_M12_N.pt`

 i changed default dir in my `comfyui\custom_nodes\comfyui_controlnet_aux\config.yaml`:
```yaml
annotator_ckpts_path: ../../ckpts
```

**Comment by Fannovel16** [comment]
Fixed in https://github.com/Fannovel16/comfyui_controlnet_aux/commit/9e9127db89a11bb048b0748d4f51fbb711aaea7a. Update the extension and it should work now
