### ISSUE TITLE
Error No module named 'midas.dpt_depth' in comfyui 

### ISSUE THREAD

**Issue by sina9977g** [Fannovel16/comfyui_controlnet_aux#330]
Recently i tried to use midas to control my image depth in comfyui and installed controlnet aux but i got some errors. Iwould really appreciate some help with  error  - No module named 'midas.dpt_depth'
I also tried previous methods of solving issue but it didnt work.

**Comment by levanly2506** [comment]
I also encountered the same situation

**Comment by blibdoolpoolp** [comment]
Me too... any fix?

**Comment by horford** [comment]
I'm also encountering this issue. Does anyone have a fix for this yet?

**Comment by schoenid** [comment]
Same to me:

```
2024-09-03 18:28:17,436 - root - ERROR - !!! Exception during processing !!! No module named 'custom_midas_repo'
2024-09-03 18:28:17,437 - root - ERROR - Traceback (most recent call last):
  File "G:\SD\Packages\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "G:\SD\Packages\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "G:\SD\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\SD\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "G:\SD\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\zoe.py", line 17, in execute
    model = ZoeDetector.from_pretrained().to(model_management.get_torch_device())
  File "G:\SD\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\zoe\__init__.py", line 25, in from_pretrained
    model = ZoeDepth.build_from_config(conf)
  File "G:\SD\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\zoe\zoedepth\models\zoedepth\zoedepth_v1.py", line 250, in build_from_config
    return ZoeDepth.build(**config)
  File "G:\SD\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\zoe\zoedepth\models\zoedepth\zoedepth_v1.py", line 240, in build
    core = MidasCore.build(midas_model_type=midas_model_type, use_pretrained_midas=use_pretrained_midas,
  File "G:\SD\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\zoe\zoedepth\models\base_models\midas.py", line 344, in build
    import custom_midas_repo
ModuleNotFoundError: No module named 'custom_midas_repo'
```

`
ComfyUI: 2643[00a5d0](2024-09-03)
Manager: V2.50.3
`

**Comment by schoenid** [comment]
Deleted the node and reinstalled it in Manager separately. (`comfyui_controlnet_aux`)

Now it's working!

It's not clear, why it was not worlking the first time.
Some thoughts:
- Maybe there was something missing from another node?
- Is the order of installing nodes important?
- Is there a missing requirement, which was fulfilled by another node, I've installed later ?
