### ISSUE TITLE
Errors when using the TTPlanet Tile Preprocessors

### ISSUE THREAD

**Issue by Davikar** [Fannovel16/comfyui_controlnet_aux#332]
Getting the following errors when I try to use the TTPlanet Tile Preprocessors:

```
!!! Exception during processing!!! module 'cv2.ximgproc' has no attribute 'guidedFilter'
Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\tile.py", line 43, in execute
    return (common_annotator_call(TTPlanet_Tile_Detector_GF(), image, scale_factor=scale_factor, blur_strength=blur_strength, radius=radius, eps=eps),)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 84, in common_annotator_call
    np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\tile\__init__.py", line 52, in __call__
    img_np = apply_guided_filter(img_np, radius, eps)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\tile\__init__.py", line 38, in apply_guided_filter
    filtered_image = cv2.ximgproc.guidedFilter(image_np_float, image_np_float, radius, eps)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'cv2.ximgproc' has no attribute 'guidedFilter'
```

```
Error occurred when executing TTPlanet_TileSimple_Preprocessor:

TTPlanet_TileSimple_Preprocessor.execute() missing 2 required positional arguments: 'radius' and 'eps'

File "C:\AI\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Everything is updated, latest version of ComfyUI etc.

**Comment by Fannovel16** [comment]
This problem seems to come from cv2 mesh 😒

**Comment by Davikar** [comment]
Forgot to add, the simple preprocessor from the custom nodes that TTPlanet provides on Civitai does work, but the advanced ones also give error messages.

**Comment by RYG81** [comment]
I have same issue with TTPlanet Tile, also it would be great to have a sample workflow for it.

**Comment by Davikar** [comment]
> I have same issue with TTPlanet Tile, also it would be great to have a sample workflow for it.

It's pretty straight forward, works just like a normal tile controlnet, you just use the ttplanet preprocessors with their controlnet.

**Comment by RYG81** [comment]
i have tried but i get error
Error occurred when executing AIO_Preprocessor:

module 'cv2.ximgproc' has no attribute 'guidedFilter'

File "D:\000AI\00ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\000AI\00ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\000AI\00ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\000AI\00ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 117, in execute
return getattr(aux_class(), aux_class.FUNCTION)(**params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\000AI\00ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\tile.py", line 43, in execute
return (common_annotator_call(TTPlanet_Tile_Detector_GF(), image, scale_factor=scale_factor, blur_strength=blur_strength, radius=radius, eps=eps),)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\000AI\00ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 84, in common_annotator_call
np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\000AI\00ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\tile\__init__.py", line 52, in __call__
img_np = apply_guided_filter(img_np, radius, eps)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\000AI\00ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\tile\__init__.py", line 38, in apply_guided_filter
filtered_image = cv2.ximgproc.guidedFilter(image_np_float, image_np_float, radius, eps)

**Comment by RYG81** [comment]
yes confirm, no more error. thank you.
