### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified

### ISSUE THREAD

**Issue by traugdor** [Fannovel16/comfyui_controlnet_aux#359]
It seems that the detailer cannot download the correct models from HF.co

```
Detailer: segment upscale for ((126.757996, 75.4863)) | crop region (634, 377) x 1.6152261499771465 -> (1024, 608)
model_path is D:\Stable Diffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\yzd-v/DWPose\yolox_l.onnx
Failed to find D:\Stable Diffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\hr16/UnJIT-DWPose\dw-ll_ucoco.onnx.
 Downloading from huggingface.co
cacher folder is C:\Users\joelt\AppData\Local\Temp, you can change it by custom_tmp_path in config.yaml
!!! Exception during processing!!! [WinError 3] The system cannot find the path specified
Traceback (most recent call last):
  File "D:\Stable Diffusion\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\Stable Diffusion\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\Stable Diffusion\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 1480, in doit
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for, max_size, seed, steps,
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 287, in do_detail
    enhanced_image, cnet_pils = core.enhance_detail(cropped_image, model, clip, vae, guide_size, guide_size_for_bbox, max_size,
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 244, in enhance_detail
    positive, negative, cnet_pils = control_net_wrapper.apply(positive, negative, upscaled_image, noise_mask)
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 1663, in apply
    cnet_image = self.preprocessor.apply(image, mask)
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\inspire\segs_support.py", line 219, in apply
    return obj.estimate_pose(image, detect_hand, detect_body, detect_face, resolution=resolution, bbox_detector=self.bbox_detector, pose_estimator=self.pose_estimator)['result'][0]
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 72, in estimate_pose
    model = DwposeDetector.from_pretrained(
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\__init__.py", line 169, in from_pretrained
    pose_model_path = custom_hf_download(pretrained_model_or_path, pose_filename)
  File "D:\Stable Diffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\util.py", line 320, in custom_hf_download
    model_path = hf_hub_download(repo_id=pretrained_model_or_path,
  File "D:\Stable Diffusion\ComfyUI\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Stable Diffusion\ComfyUI\venv\lib\site-packages\huggingface_hub\file_download.py", line 1427, in hf_hub_download
    _check_disk_space(expected_size, local_dir)
  File "D:\Stable Diffusion\ComfyUI\venv\lib\site-packages\huggingface_hub\file_download.py", line 975, in _check_disk_space
    target_dir_free = shutil.disk_usage(target_dir).free
  File "C:\Python310\lib\shutil.py", line 1340, in disk_usage
    total, free = nt._getdiskusage(path)
FileNotFoundError: [WinError 3] The system cannot find the path specified
```

**Comment by traugdor** [comment]
Previously posted here: https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/611 and was asked to post in this repo instead.
