### ISSUE TITLE
no module named 'matplotlib' when using openpose pose node

### ISSUE THREAD

**Issue by deathtome1998** [Fannovel16/comfyui_controlnet_aux#364]
I'm trying these custom nodes for the first time with my first runs of comfyui, and I am getting the modulenotfounderror: no module named 'matplotlib' whenever I try to start a image generation with the openpose pose node in the workflow. I don't know if anything else would work as I haven't tried them, mostly because I'm not sure how much I'd ever end up using them compared to openpose. 
here's a paste of my traceback in my command terminal. 

!!! Exception during processing!!! No module named 'matplotlib'
Traceback (most recent call last):
  File "B:\_StableDiff\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\_StableDiff\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\_StableDiff\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\_StableDiff\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\openpose.py", line 20, in estimate_pose
    from controlnet_aux.open_pose import OpenposeDetector
  File "B:\_StableDiff\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\open_pose\__init__.py", line 25, in <module>
    from . import util
  File "B:\_StableDiff\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\open_pose\util.py", line 3, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib' 

hope someone can help. thanks in advance.

**Comment by injet-zhou** [comment]
Use `pip install matplotlib` to install the missing dependency.

**Comment by jahinmahbub** [comment]
Thanks

**Comment by ZELBIO** [comment]
> Use `pip install matplotlib` to install the missing dependency.

how? Install in system python, not in the COMFYUI embeded phyton folder .

**Comment by Adelamus** [comment]
> Use `pip install matplotlib` to install the missing dependency.

If I use that command, it tells me: "Requirement already satisfied" too all of the things

**Comment by AlcDesk0** [comment]
> > Use `pip install matplotlib` to install the missing dependency.
> 
> If I use that command, it tells me: "Requirement already satisfied" too all of the things

If you are using Anaconda to run Comfyui, then do the following:

Open Anaconda and use the command: call conda activate comfyui

Then: pip install matplotlib

It should work. I don't know why it happens, but using Anaconda it recognizes it as another installation location, in this case the exact location of Comfy for me.
