### ISSUE TITLE
Perform Anyline preprocessing，TypeError: TEDDetector.from_pretrained() got an unexpected keyword argument 'subfolder'

### ISSUE THREAD

**Issue by WangGosh** [Fannovel16/comfyui_controlnet_aux#373]
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-06-06 07:32:55.127223
** Platform: Linux
** Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
** Python executable: /opt/conda/bin/python
** Log path: /mnt/workspace/ComfyUI/comfyui.log

Total VRAM 22732 MB, total RAM 30149 MB
pytorch version: 2.1.2+cu121
xformers version: 0.0.23.post1
Forcing FP16.
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA A10 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
------------------------------------------------------------The above is the execution system environment

The following is the execution error content:
got prompt
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing!!! TEDDetector.from_pretrained() got an unexpected keyword argument 'subfolder'
Traceback (most recent call last):
  File "/mnt/workspace/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/mnt/workspace/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/mnt/workspace/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/mnt/workspace/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/anyline.py", line 53, in get_anyline
    mteed_model = TEDDetector.from_pretrained("TheMistoAI/MistoLine", "MTEED.pth", subfolder="Anyline").to(self.device)
TypeError: TEDDetector.from_pretrained() got an unexpected keyword argument 'subfolder'

Prompt executed in 0.00 seconds

![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/163592591/a202c49f-28a4-4fdb-9e65-9b5224fa22f0)

**Comment by YDBZ** [comment]
سلام
در پوشه custom_nodes\comfyui_controlnet_aux\node_wrappers فایل anyline.py را توسط idle باز کنید
خط 53 را به شکل زیر تغییر دهید:
mteed_model=TEDDetector.from_pretrained().to(self.device)
فایل را توسط Ctrl+S ذخیره کنید
در مسیر comfyui_controlnet_aux\ckpts\bdsqlsz\qinqlong_controlnet-lllite\annotators مطمئن شوید که فایل  7-model.pth موجود باشد
اگر وجود نداشت از مسیر زیر دانلود کنید و قرار دهید
https://huggingface.co/bdsqlsz/qinglong_controlnet-lllite/blob/main/Annotators/7_model.pth
ان شاءالله مشکل برطرف بشود

**Comment by xiaowuzicode** [comment]
Hello, has this issue been resolved?

**Comment by irongourd** [comment]
Has anyone solved this problem？

**Comment by WangGosh** [comment]
> 有谁解决过这个问题吗？

I later solved it myself, but I forgot how to operate it. I remember modifying the code and downloading the configuration model

**Comment by WangGosh** [comment]
> 您好，这个问题解决了吗？

I later solved it myself, but I forgot how to operate it. I remember modifying the code and downloading the configuration model

**Comment by emourdavid** [comment]
Open anyline.py and replace line 9 - 10 -11 with

from custom_nodes.comfyui_controlnet_aux.src.custom_controlnet_aux.teed import TEDDetector
from custom_nodes.comfyui_controlnet_aux.src.custom_controlnet_aux.teed.ted import TED
from custom_nodes.comfyui_controlnet_aux.src.custom_controlnet_aux.lineart_standard import LineartStandardDetector
