### ISSUE TITLE
All Preprocessor ModuleNotFoundError after update

### ISSUE THREAD

**Issue by whmc76** [Fannovel16/comfyui_controlnet_aux#389]
<img width="528" alt="1719477107400" src="https://github.com/Fannovel16/comfyui_controlnet_aux/assets/129386342/2674ce8a-b455-4f94-93dc-b45dc6c226d0">

**Comment by whmc76** [comment]
E:\IMAGE\ComfyUI_master>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-06-27 16:42:48.593643
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: E:\IMAGE\ComfyUI_master\python_embeded\python.exe
** Log path: E:\IMAGE\ComfyUI_master\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.8 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 49140 MB, total RAM 64663 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX 6000 Ada Generation : cudaMallocAsync
Using xformers cross attention
[Allor]: No new updates.
[Allor]: 0 nodes were overridden.
[Allor]: 12 modules were enabled.
[Allor]: 98 nodes were loaded.
[Crystools INFO] Crystools version: 1.12.0
[Crystools INFO] CPU: Unknown - Arch: Unknown - OS: Windows 10
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA RTX 6000 Ada Generation
[Crystools INFO] NVIDIA Driver: 552.23
Comfy-Easy-Use v1.2.0: Loaded
Total VRAM 49140 MB, total RAM 64663 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX 6000 Ada Generation : cudaMallocAsync
E:\IMAGE\ComfyUI_master\python_embeded\Lib\site-packages\diffusers\models\dual_transformer_2d.py:20: FutureWarning: `DualTransformer2DModel` is deprecated and will be removed in version 0.29. Importing `DualTransformer2DModel` from `diffusers.models.dual_transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.transformers.dual_transformer_2d import DualTransformer2DModel`, instead.
  deprecate("DualTransformer2DModel", "0.29", deprecation_message)
E:\IMAGE\ComfyUI_master\python_embeded\Lib\site-packages\diffusers\models\transformer_2d.py:20: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 0.29. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.transformers.transformer_2d import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "0.29", deprecation_message)
E:\IMAGE\ComfyUI_master\python_embeded\Lib\site-packages\diffusers\models\transformer_2d.py:25: FutureWarning: `Transformer2DModel` is deprecated and will be removed in version 0.29. Importing `Transformer2DModel` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.transformers.transformer_2d import Transformer2DModel`, instead.
  deprecate("Transformer2DModel", "0.29", deprecation_message)
### Loading: ComfyUI-Impact-Pack (V5.18.3)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V0.80.4)
### Loading: ComfyUI-Manager (V2.42)
### ComfyUI Revision: 2295 [4f9d2b05] | Released on '2024-06-27'
--------------
 ### Mixlab Nodes: Loaded
ChatGPT.available True
edit_mask.available True
LaMaInpainting.available True
ClipInterrogator.available True
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
TripoSR.available
 --------------
[ReActor] - STATUS - Running v0.5.0-b4 in ComfyUI
Torch version: 2.3.0+cu121
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: AzureExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
Workspace manager - Openning file hash dict
🦄🦄Loading: Workspace Manager (V2.1.0)
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']


Full error log from comfyui_controlnet_aux:
Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 32, in load_nodes
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 5, in <module>
    from controlnet_aux.dwpose import DwposeDetector, AnimalposeDetector
ImportError: cannot import name 'DwposeDetector' from 'controlnet_aux.dwpose' (E:\IMAGE\ComfyUI_master\python_embeded\Lib\site-packages\controlnet_aux\dwpose\__init__.py)


Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 32, in load_nodes
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\pose_keypoint_postprocess.py", line 11, in <module>
    from ..src.controlnet_aux.dwpose import draw_poses, draw_animalposes, decode_json_as_poses
  File "E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\__init__.py", line 21, in <module>
    from .wholebody import Wholebody
  File "E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\wholebody.py", line 16, in <module>
    from controlnet_aux.dwpose.util import guess_onnx_input_shape_dtype, get_model_type, get_ort_providers, is_model_torchscript
ImportError: cannot import name 'guess_onnx_input_shape_dtype' from 'controlnet_aux.dwpose.util' (E:\IMAGE\ComfyUI_master\python_embeded\Lib\site-packages\controlnet_aux\dwpose\util.py)



[comfyui_controlnet_aux] | INFO -> Some nodes failed to load:
        Failed to import module dwpose because ImportError: cannot import name 'DwposeDetector' from 'controlnet_aux.dwpose' (E:\IMAGE\ComfyUI_master\python_embeded\Lib\site-packages\controlnet_aux\dwpose\__init__.py)
        Failed to import module pose_keypoint_postprocess because ImportError: cannot import name 'guess_onnx_input_shape_dtype' from 'controlnet_aux.dwpose.util' (E:\IMAGE\ComfyUI_master\python_embeded\Lib\site-packages\controlnet_aux\dwpose\util.py)

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/Fannovel16/comfyui_controlnet_aux/issues)
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
FizzleDorf Custom Nodes: Loaded
# 😺dzNodes: LayerStyle -> Cannot import name 'guidedFilter' from 'cv2.ximgproc'
A few nodes cannot works properly, while most nodes are not affected. Please REINSTALL package 'opencv-contrib-python'.
For detail refer to https://github.com/chflame163/ComfyUI_LayerStyle/issues/5
# 😺dzNodes: LayerStyle -> Warning: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Find 1 LUTs in E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI_LayerStyle\lut
# 😺dzNodes: LayerStyle -> Find 1 Fonts in E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI_LayerStyle\font
All packages from requirements.txt are installed and up to date.
llama-cpp installed
All packages from requirements.txt are installed and up to date.
AutoGPTQ installed
[comfy_mtb] | INFO -> loaded 77 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
[comfyui_controlnet_aux] | INFO -> Some nodes failed to load:
        Failed to import module dwpose because ImportError: cannot import name 'DwposeDetector' from 'controlnet_aux.dwpose' (E:\IMAGE\ComfyUI_master\python_embeded\Lib\site-packages\controlnet_aux\dwpose\__init__.py)
        Failed to import module pose_keypoint_postprocess because ImportError: cannot import name 'guess_onnx_input_shape_dtype' from 'controlnet_aux.dwpose.util' (E:\IMAGE\ComfyUI_master\python_embeded\Lib\site-packages\controlnet_aux\dwpose\util.py)

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/Fannovel16/comfyui_controlnet_aux/issues)
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI_master\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\IMAGE\\ComfyUI_master\\ComfyUI\\custom_nodes\\huggingface\\__init__.py'

Cannot import E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\huggingface module for custom nodes: [Errno 2] No such file or directory: 'E:\\IMAGE\\ComfyUI_master\\ComfyUI\\custom_nodes\\huggingface\\__init__.py'
Please 'pip install apex'

[rgthree] Loaded 40 epic nodes.
[rgthree] Will use rgthree's optimized recursive execution.

WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 217 nodes successfully.

        "The distance between insanity and genius is measured only by success." - Bruce Feirstein


Import times for custom nodes:
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui-profiler
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\style_aligned_comfy
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds (IMPORT FAILED): E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\huggingface
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\Lora-Training-in-Comfy
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-SDXL-EmptyLatentImage
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\cg-image-picker
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Lora-Auto-Trigger-Words
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI_densediffusion
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-ELLA
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Loopchain
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui_jankhidiffusion
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui-inpaint-nodes
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI_omost
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Text_Image-Composite
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui-various
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\steerable-motion
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Florence2
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI_ExtraModels
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\Comfyui-ChatTTS
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-IC-Light
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI_ProPainter_Nodes
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-SUPIR
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\OneButtonPrompt
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui-workspace-manager
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfy_mtb
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-IDM-VTON
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Qwen-VL-API
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-ToonCrafter
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui_segment_anything
   0.0 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.1 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI_LayerStyle
   0.1 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\PuLID_ComfyUI
   0.1 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.1 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-BrushNet
   0.1 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui-sound-lab
   0.1 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI_VLM_nodes
   0.1 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.1 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.1 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.1 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui-reactor-node
   0.2 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.2 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio
   0.3 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-APISR-KJ
   0.4 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.4 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Gemini
   0.7 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui-mixlab-nodes
   0.8 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-CCSR
   1.2 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\was-node-suite-comfyui
   2.2 seconds: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Allor

https_key OK:  E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui-mixlab-nodes\https\certificate.crt E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui-mixlab-nodes\https\private.key




Starting server
To see the GUI go to: http://127.0.0.1:8188
To see the GUI go to: https://127.0.0.1:8189
FETCH DATA from: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
# 😺dzNodes: LayerStyle -> Warning: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
start_local_llm error
# 😺dzNodes: LayerStyle -> Warning: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
#read_workflow_json_files_all E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui-mixlab-nodes\app\
got prompt
[rgthree] Using rgthree's optimized recursive execution.
[rgthree] First run patching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
# 😺dzNodes: LayerStyle -> ImageScaleByAspectRatio V2 Processed 1 image(s).
using flash_attention_2 for attention
</s><s><s><s>A blurry image of a rainbow colored background.</s>
[EasyUse] 正在加载模型...
model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
[EasyUse] Load LORA: 艺术风格\miniatureWorldStyle_v10.safetensors: 0.8, 0.8, LBW=None, A=None, B=None
[EasyUse] 正在进行正面提示词...
[EasyUse] easy wildcards: positive: minimalist style mini\(ttp\), A blurry image of a rainbow colored background. . simple, clean, uncluttered, modern, elegant
[EasyUse] 正在进行正面提示词编码...
Requested to load SD1ClipModel
Loading 1 new model
[EasyUse] 正在进行负面提示词...
[EasyUse] easy wildcards: negative: ornate, complicated, highly detailed, cluttered, disordered, messy, noisy
[EasyUse] 正在进行负面提示词编码...
Requested to load SD1ClipModel
Loading 1 new model
[EasyUse] 加载完毕...
!!! Exception during processing!!! No module named 'controlnet_aux.depth_anything_v2'
Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI_master\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_master\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_master\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 117, in execute
    return getattr(aux_class(), aux_class.FUNCTION)(**params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\depth_anything_v2.py", line 17, in execute
    from controlnet_aux.depth_anything_v2 import DepthAnythingV2Detector
ModuleNotFoundError: No module named 'controlnet_aux.depth_anything_v2'

[profiler] #21 ScreenShare: 0.0037 seconds, total 0.0037 seconds
[profiler] #16 LayerUtility: ImageScaleByAspectRatio V2: 0.0195 seconds, total 0.0232 seconds(#21)
[profiler] #24 easy imagePixelPerfect: 0.0011 seconds, total 0.0244 seconds(#16)
[profiler] #36 LoraLoaderStackedVanilla: 0.0028 seconds, total 0.0028 seconds
[profiler] #32 TagsSelector: 0.0008 seconds, total 0.0037 seconds(#36)
[profiler] #31 easy showAnything: 0.0008 seconds, total 0.0044 seconds(#32)
[profiler] #13 DownloadAndLoadFlorence2Model: 1.8128 seconds, total 1.8128 seconds
[profiler] #12 Florence2Run: 0.4338 seconds, total 2.2699 seconds(#16 #13)
[profiler] #28 Text Concatenate: 0.0008 seconds, total 2.2743 seconds(#32 #12)
[profiler] #11 easy stylesSelector: 0.0011 seconds, total 2.2754 seconds(#28)
[profiler] #10 easy fullLoader: 1.1109 seconds, total 3.3892 seconds(#16 #16 #11 #11 #36)
[profiler] #46 AIO_Preprocessor: 0.0749 seconds, total 0.0993 seconds(#24 #16)
[profiler] #22 easy controlnetLoaderADV: 0.0016 seconds, total 3.49 seconds(#10 #46)
Prompt executed in 3.47 seconds
