### ISSUE TITLE
NameError: name 'os' is not defined

### ISSUE THREAD

**Issue by Davikar** [Fannovel16/comfyui_controlnet_aux#4]
Getting this error when starting ComfyUI:

```
Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\nodes.py", line 1688, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 11, in <module>
    for pkg_name in os.listdir(str(Path(here, "src"))):
NameError: name 'os' is not defined
```
Running latest build of ComfyUI on Windows 11, Python 3.10.11.

**Comment by Fannovel16** [comment]
Oops. I forgot to import os. Fixed.
