### ISSUE TITLE
When I used DWPose node, it threw the error

### ISSUE THREAD

**Issue by flybirdxx** [Fannovel16/comfyui_controlnet_aux#401]
![QQ截图20240713142541](https://github.com/user-attachments/assets/0eb36123-9e6f-47d5-8912-4531053c59e9)
DWPose: Using yolox_l.onnx for bbox detection and dw-ll_ucoco_384_bs5.torchscript.pt for pose estimation
=:a\neor\ =r=c(c__atdaa __rsea,
s wlon a_aMsNfDSG;EAlo\nre7 =uorwnl_trs_._wd,s.ns,s.gt(,wkspaebea,st.
!!! Exception during processing!!! [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Conv node. Name:'Conv_41' Status Message: CUDNN failure 2000: CUDNN_STATUS_BAD_PARAM ; GPU=0 ; hostname=DESKTOP-E1A27JF ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\nn\conv.cc ; line=467 ; expr=cudnnConvolutionForward(cudnn_handle, &alpha, s_.x_tensor, s_.x_data, s_.w_desc, s_.w_data, s_.conv_desc, s_.algo, workspace.get(), s_.workspace_bytes, &beta, s_.y_tensor, s_.y_data);
Traceback (most recent call last):
  File "E:\ComfyUI-aki-v1.3\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 87, in estimate_pose
    out = common_annotator_call(func, image, include_hand=detect_hand, include_face=detect_face, include_body=detect_body, image_and_json=True, resolution=resolution)
  File "E:\ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux\utils.py", line 85, in common_annotator_call
    np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)
  File "E:\ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 83, in func
    pose_img, openpose_dict = model(image, **kwargs)
  File "E:\ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\__init__.py", line 262, in __call__
    poses = self.detect_poses(input_image)
  File "E:\ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\__init__.py", line 252, in detect_poses
    keypoints_info = self.dw_pose_estimation(oriImg.copy())
  File "E:\ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\wholebody.py", line 88, in __call__
    det_result = inference_onnx_yolox(self.det, oriImg, detect_classes=[0], dtype=np.float32)
  File "E:\ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\dw_onnx\cv_ox_det.py", line 104, in inference_detector
    output = session.run(None, {input_name: input})
  File "E:\ComfyUI-aki-v1.3\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Conv node. Name:'Conv_41' Status Message: CUDNN failure 2000: CUDNN_STATUS_BAD_PARAM ; GPU=0 ; hostname=DESKTOP-E1A27JF ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\nn\conv.cc ; line=467 ; expr=cudnnConvolutionForward(cudnn_handle, &alpha, s_.x_tensor, s_.x_data, s_.w_desc, s_.w_data, s_.conv_desc, s_.algo, workspace.get(), s_.workspace_bytes, &beta, s_.y_tensor, s_.y_data);

The above is the error message. Could you help me find out what caused the problem? Thank you.

**Comment by flybirdxx** [comment]
![Uploading QQ截图.png…]()

**Comment by flybirdxx** [comment]
![QQ截图](https://github.com/user-attachments/assets/b42c7ed0-6c51-4a9a-886c-3f740f5a263f)
