### ISSUE TITLE
DWPose Estimator fails after the ComplyUI update.

### ISSUE THREAD

**Issue by Neytiri7** [Fannovel16/comfyui_controlnet_aux#429]
Error occurred when executing DWPreprocessor:

A:\SynologyDrive\ComfyUI-webui\python_embeded\python311.zip\distutils\core.pyc

File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 316, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 191, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 168, in _map_node_over_list
process_inputs(input_dict, i)
File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 157, in process_inputs
results.append(getattr(obj, func)(**inputs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 87, in estimate_pose
out = common_annotator_call(func, image, include_hand=detect_hand, include_face=detect_face, include_body=detect_body, image_and_json=True, resolution=resolution)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 85, in common_annotator_call
np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 83, in func
pose_img, openpose_dict = model(image, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^
File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\__init__.py", line 262, in __call__
poses = self.detect_poses(input_image)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\__init__.py", line 252, in detect_poses
keypoints_info = self.dw_pose_estimation(oriImg.copy())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\wholebody.py", line 80, in __call__
import torch.utils.benchmark.utils.timer as torch_timer
File "A:\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\torch\utils\benchmark\utils\timer.py", line 8, in
from torch.utils.benchmark.utils import common, cpp_jit
File "A:\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\torch\utils\benchmark\utils\cpp_jit.py", line 13, in
from torch.utils import cpp_extension
File "A:\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 9, in
import setuptools
File "A:\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\setuptools\__init__.py", line 8, in
import _distutils_hack.override # noqa: F401
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "A:\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\_distutils_hack\override.py", line 1, in
__import__('_distutils_hack').do_override()
File "A:\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\_distutils_hack\__init__.py", line 70, in do_override
ensure_local_distutils()
File "A:\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\_distutils_hack\__init__.py", line 57, in ensure_local_distutils
assert '_distutils' in core.__file__, core.__file__
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Neytiri7** [comment]
model_path is A:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\hr16/yolox-onnx\yolox_l.torchscript.pt
model_path is A:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\hr16/DWPose-TorchScript-BatchSize5\dw-ll_ucoco_384_bs5.torchscript.pt

DWPose: Using yolox_l.torchscript.pt for bbox detection and dw-ll_ucoco_384_bs5.torchscript.pt for pose estimation
!!! Exception during processing !!! A:\SynologyDrive\ComfyUI-webui\python_embeded\python311.zip\distutils\core.pyc
Traceback (most recent call last):
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 316, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 191, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 168, in _map_node_over_list
    process_inputs(input_dict, i)
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 157, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 87, in estimate_pose
    out = common_annotator_call(func, image, include_hand=detect_hand, include_face=detect_face, include_body=detect_body, image_and_json=True, resolution=resolution)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 85, in common_annotator_call
    np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 83, in func
    pose_img, openpose_dict = model(image, **kwargs)
                              ^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\__init__.py", line 262, in __call__
    poses = self.detect_poses(input_image)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\__init__.py", line 252, in detect_poses
    keypoints_info = self.dw_pose_estimation(oriImg.copy())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\wholebody.py", line 80, in __call__
    import torch.utils.benchmark.utils.timer as torch_timer
  File "A:\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\torch\utils\benchmark\utils\timer.py", line 8, in <module>
    from torch.utils.benchmark.utils import common, cpp_jit
  File "A:\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\torch\utils\benchmark\utils\cpp_jit.py", line 13, in <module>
    from torch.utils import cpp_extension
  File "A:\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 9, in <module>
    import setuptools
  File "A:\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\setuptools\__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\_distutils_hack\override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "A:\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\_distutils_hack\__init__.py", line 70, in do_override
    ensure_local_distutils()
  File "A:\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\_distutils_hack\__init__.py", line 57, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: A:\SynologyDrive\ComfyUI-webui\python_embeded\python311.zip\distutils\core.pyc

**Comment by lanse6899** [comment]
I got the same error.

**Comment by Fannovel16** [comment]
Fixed at https://github.com/Fannovel16/comfyui_controlnet_aux/commit/4cd233c5d7afe2e51bf57ee7a5ba7e6fcb9cbb22
