### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by laidingq** [Fannovel16/comfyui_controlnet_aux#430]
[ERROR] An error occurred while retrieving information for the 'DepthAnythingPreprocessor' node.
Traceback (most recent call last):
  File "D:\ComfyUI\server.py", line 452, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\ComfyUI\server.py", line 425, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\depth_anything.py", line 8, in INPUT_TYPES
    ckpt_name=INPUT.COMBO(
              ^^^^^^^^^^^^
TypeError: INPUT.COMBO() got an unexpected keyword argument 'resolution'

[ERROR] An error occurred while retrieving information for the 'ImageIntensityDetector' node.
Traceback (most recent call last):
  File "D:\ComfyUI\server.py", line 452, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\ComfyUI\server.py", line 426, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by jasoncow007** [comment]
same issue，after updated

**Comment by vootox** [comment]
Exact same error, I thought I was the only one but glad I'm not!

**Comment by Shingkyo** [comment]
I revert back to the older version till fix proposed...
