### ISSUE TITLE
error occurred while retrieving information for the 'DepthAnythingPreprocessor' node

### ISSUE THREAD

**Issue by whmc76** [Fannovel16/comfyui_controlnet_aux#431]
[ERROR] An error occurred while retrieving information for the 'DepthAnythingPreprocessor' node.
Traceback (most recent call last):
  File "E:\ComfyUI_MainTask\ComfyUI\server.py", line 447, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\ComfyUI_MainTask\ComfyUI\server.py", line 424, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_MainTask\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\depth_anything.py", line 8, in INPUT_TYPES
    ckpt_name=INPUT.COMBO(
              ^^^^^^^^^^^^
TypeError: INPUT.COMBO() got an unexpected keyword argument 'resolution'

**Comment by ElSuccerro** [comment]
Same here:

[ERROR] An error occurred while retrieving information for the 'DepthAnythingPreprocessor' node.
Traceback (most recent call last):
  File "A:\ComfyUI_2.4Up\ComfyUI\server.py", line 452, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "A:\ComfyUI_2.4Up\ComfyUI\server.py", line 425, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyUI_2.4Up\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\depth_anything.py", line 8, in INPUT_TYPES
    ckpt_name=INPUT.COMBO(
              ^^^^^^^^^^^^
TypeError: INPUT.COMBO() got an unexpected keyword argument 'resolution'

[ERROR] An error occurred while retrieving information for the 'ImageIntensityDetector' node.
Traceback (most recent call last):
  File "A:\ComfyUI_2.4Up\ComfyUI\server.py", line 452, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "A:\ComfyUI_2.4Up\ComfyUI\server.py", line 426, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by Nikosis** [comment]
Same here
