### ISSUE TITLE
'DepthAnythingPreprocessor' node error

### ISSUE THREAD

**Issue by DonDanDojo** [Fannovel16/comfyui_controlnet_aux#432]
Hi. I got an recent error regarding this node. Could it be due to Comfy recent update?

FETCH DATA from: X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ERROR] An error occurred while retrieving information for the 'DepthAnythingPreprocessor' node.
Traceback (most recent call last):
  File "X:\SD Launcher\SD nowy\Packages\ComfyUI\server.py", line 447, in get_object_info
    out[x] = node_info(x)
  File "X:\SD Launcher\SD nowy\Packages\ComfyUI\server.py", line 424, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "X:\SD Launcher\SD nowy\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\depth_anything.py", line 8, in INPUT_TYPES
    ckpt_name=INPUT.COMBO(
TypeError: INPUT.COMBO() got an unexpected keyword argument 'resolution'

**Comment by Fannovel16** [comment]
It's due to a typo in this extension's code. I just fixed it recently

**Comment by DonDanDojo** [comment]
> It's due to a typo in this extension's code. I just fixed it recently

Thank you for reply. Fixed.
