### ISSUE TITLE
epth 使用不了，一直报错：Zoe深度预处理器 PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by liushijiejob** [Fannovel16/comfyui_controlnet_aux#455]
![screenshot-20240913-111744](https://github.com/user-attachments/assets/445d70cf-13fa-44e1-8ef8-ecada8ada7f9)
Debug Lods:
# ComfyUI Error Report
## Error Details
- **Node Type:** Zoe-DepthMapPreprocessor
- **Exception Type:** RuntimeError
- **Exception Message:** PytorchStreamReader failed reading zip archive: failed finding central directory
## Stack Trace

  File "H:\ComfyUI-aki-v1.2\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "H:\ComfyUI-aki-v1.2\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "H:\ComfyUI-aki-v1.2\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "H:\ComfyUI-aki-v1.2\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "H:\ComfyUI-aki-v1.2\custom_nodes\comfyui_controlnet_aux\node_wrappers\zoe.py", line 17, in execute
    model = ZoeDetector.from_pretrained().to(model_management.get_torch_device())

  File "H:\ComfyUI-aki-v1.2\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\zoe\__init__.py", line 26, in from_pretrained
    model.load_state_dict(torch.load(model_path, map_location=torch.device('cpu'))['model'])

  File "H:\ComfyUI-aki-v1.2\python\lib\site-packages\torch\serialization.py", line 993, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:

  File "H:\ComfyUI-aki-v1.2\python\lib\site-packages\torch\serialization.py", line 447, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))

Logs：
2024-09-11 18:31:14,967 - root - INFO - Total VRAM 11264 MB, total RAM 16337 MB
2024-09-11 18:31:14,967 - root - INFO - pytorch version: 2.1.2+cu118
2024-09-11 18:31:15,272 - root - INFO - xformers version: 0.0.23.post1+cu118
2024-09-11 18:31:15,272 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-11 18:31:15,272 - root - INFO - Device: cuda:0 NVIDIA GeForce GTX 1080 Ti : native
2024-09-11 18:31:16,451 - root - INFO - Using xformers cross attention
2024-09-11 18:31:17,201 - root - INFO - [Prompt Server] web root: H:\ComfyUI-aki-v1.2\web
2024-09-11 18:31:17,217 - root - INFO - Adding extra search path checkpoints H:\sd-webui-aki-v4.6.1\models/Stable-diffusion
2024-09-11 18:31:17,217 - root - INFO - Adding extra search path configs H:\sd-webui-aki-v4.6.1\models/Stable-diffusion
2024-09-11 18:31:17,217 - root - INFO - Adding extra search path vae H:\sd-webui-aki-v4.6.1\models/VAE
2024-09-11 18:31:17,217 - root - INFO - Adding extra search path loras H:\sd-webui-aki-v4.6.1\models/Lora
2024-09-11 18:31:17,217 - root - INFO - Adding extra search path loras H:\sd-webui-aki-v4.6.1\models/LyCORIS
2024-09-11 18:31:17,217 - root - INFO - Adding extra search path upscale_models H:\sd-webui-aki-v4.6.1\models/ESRGAN
2024-09-11 18:31:17,217 - root - INFO - Adding extra search path upscale_models H:\sd-webui-aki-v4.6.1\models/RealESRGAN
2024-09-11 18:31:17,217 - root - INFO - Adding extra search path upscale_models H:\sd-webui-aki-v4.6.1\models/SwinIR
2024-09-11 18:31:17,217 - root - INFO - Adding extra search path embeddings H:\sd-webui-aki-v4.6.1\embeddings
2024-09-11 18:31:17,217 - root - INFO - Adding extra search path hypernetworks H:\sd-webui-aki-v4.6.1\models/hypernetworks
2024-09-11 18:31:17,217 - root - INFO - Adding extra search path controlnet H:\sd-webui-aki-v4.6.1\models\ControlNet
2024-09-11 18:31:18,107 - root - WARNING - Traceback (most recent call last):
  File "H:\ComfyUI-aki-v1.2\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ComfyUI-aki-v1.2\comfy_extras\nodes_audio.py", line 1, in <module>
    import torchaudio
ModuleNotFoundError: No module named 'torchaudio'

2024-09-11 18:31:18,107 - root - WARNING - Cannot import H:\ComfyUI-aki-v1.2\comfy_extras\nodes_audio.py module for custom nodes: No module named 'torchaudio'
2024-09-11 18:31:26,857 - root - INFO - Total VRAM 11264 MB, total RAM 16337 MB
2024-09-11 18:31:26,857 - root - INFO - pytorch version: 2.1.2+cu118
2024-09-11 18:31:26,857 - root - INFO - xformers version: 0.0.23.post1+cu118
2024-09-11 18:31:26,857 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-11 18:31:26,857 - root - INFO - Device: cuda:0 NVIDIA GeForce GTX 1080 Ti : native
2024-09-11 18:31:36,593 - root - WARNING - Traceback (most recent call last):
  File "H:\ComfyUI-aki-v1.2\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'H:\\ComfyUI-aki-v1.2\\custom_nodes\\ComfyUI_FaceAnalysis\\__init__.py'

2024-09-11 18:31:36,593 - root - WARNING - Cannot import H:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_FaceAnalysis module for custom nodes: [Errno 2] No such file or directory: 'H:\\ComfyUI-aki-v1.2\\custom_nodes\\ComfyUI_FaceAnalysis\\__init__.py'
2024-09-11 18:31:37,095 - root - INFO - 
Import times for custom nodes:
2024-09-11 18:31:37,095 - root - INFO -    0.0 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\websocket_image_save.py
2024-09-11 18:31:37,095 - root - INFO -    0.0 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\AIGODLIKE-ComfyUI-Translation
2024-09-11 18:31:37,095 - root - INFO -    0.0 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\ControlNet-LLLite-ComfyUI
2024-09-11 18:31:37,095 - root - INFO -    0.0 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_TiledKSampler
2024-09-11 18:31:37,095 - root - INFO -    0.0 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\stability-ComfyUI-nodes
2024-09-11 18:31:37,096 - root - INFO -    0.0 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-WD14-Tagger
2024-09-11 18:31:37,096 - root - INFO -    0.0 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_experiments
2024-09-11 18:31:37,096 - root - INFO -    0.0 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\PowerNoiseSuite
2024-09-11 18:31:37,096 - root - INFO -    0.0 seconds (IMPORT FAILED): H:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_FaceAnalysis
2024-09-11 18:31:37,096 - root - INFO -    0.0 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\images-grid-comfy-plugin
2024-09-11 18:31:37,096 - root - INFO -    0.0 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_UltimateSDUpscale
2024-09-11 18:31:37,096 - root - INFO -    0.0 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Custom-Scripts
2024-09-11 18:31:37,096 - root - INFO -    0.0 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Frame-Interpolation
2024-09-11 18:31:37,096 - root - INFO -    0.0 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-09-11 18:31:37,096 - root - INFO -    0.0 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Advanced-ControlNet
2024-09-11 18:31:37,096 - root - INFO -    0.0 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\efficiency-nodes-comfyui
2024-09-11 18:31:37,096 - root - INFO -    0.0 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\FreeU_Advanced
2024-09-11 18:31:37,096 - root - INFO -    0.0 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_IPAdapter_plus
2024-09-11 18:31:37,096 - root - INFO -    0.0 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-09-11 18:31:37,096 - root - INFO -    0.0 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\comfyui-workspace-manager
2024-09-11 18:31:37,096 - root - INFO -    0.0 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Marigold
2024-09-11 18:31:37,097 - root - INFO -    0.1 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-09-11 18:31:37,097 - root - INFO -    0.1 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\comfyui_controlnet_aux
2024-09-11 18:31:37,097 - root - INFO -    0.1 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Crystools
2024-09-11 18:31:37,097 - root - INFO -    0.1 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Inspire-Pack
2024-09-11 18:31:37,097 - root - INFO -    0.4 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_FizzNodes
2024-09-11 18:31:37,097 - root - INFO -    0.5 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Manager
2024-09-11 18:31:37,097 - root - INFO -    0.8 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\comfyui-instantId-faceswap
2024-09-11 18:31:37,097 - root - INFO -    7.2 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Impact-Pack
2024-09-11 18:31:37,097 - root - INFO -    9.6 seconds: H:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-09-11 18:31:37,097 - root - INFO - 
2024-09-11 18:31:37,097 - root - WARNING - WARNING: some comfy_extras/ nodes did not import correctly. This may be because they are missing some dependencies.

2024-09-11 18:31:37,097 - root - WARNING - IMPORT FAILED: nodes_audio.py
2024-09-11 18:31:37,097 - root - WARNING - 
This issue might be caused by new missing dependencies added the last time you updated ComfyUI.
2024-09-11 18:31:37,097 - root - WARNING - Please do a: pip install -r requirements.txt
2024-09-11 18:31:37,097 - root - WARNING - 
2024-09-11 18:31:37,107 - root - INFO - Starting server

2024-09-11 18:31:37,107 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-11 18:31:46,156 - root - INFO - got prompt
2024-09-11 18:31:52,834 - root - ERROR - !!! Exception during processing !!! PytorchStreamReader failed reading zip archive: failed finding central directory
2024-09-11 18:31:52,836 - root - ERROR - Traceback (most recent call last):
  File "H:\ComfyUI-aki-v1.2\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "H:\ComfyUI-aki-v1.2\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "H:\ComfyUI-aki-v1.2\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "H:\ComfyUI-aki-v1.2\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "H:\ComfyUI-aki-v1.2\custom_nodes\comfyui_controlnet_aux\node_wrappers\zoe.py", line 17, in execute
    model = ZoeDetector.from_pretrained().to(model_management.get_torch_device())
  File "H:\ComfyUI-aki-v1.2\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\zoe\__init__.py", line 26, in from_pretrained
    model.load_state_dict(torch.load(model_path, map_location=torch.device('cpu'))['model'])
  File "H:\ComfyUI-aki-v1.2\python\lib\site-packages\torch\serialization.py", line 993, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "H:\ComfyUI-aki-v1.2\python\lib\site-packages\torch\serialization.py", line 447, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

2024-09-11 18:31:52,837 - root - INFO - Prompt executed in 6.67 seconds
2024-09-11 18:32:13,602 - root - INFO - got prompt
2024-09-11 18:32:18,578 - root - ERROR - !!! Exception during processing !!! PytorchStreamReader failed reading zip archive: failed finding central directory
2024-09-11 18:32:18,578 - root - ERROR - Traceback (most recent call last):
  File "H:\ComfyUI-aki-v1.2\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "H:\ComfyUI-aki-v1.2\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "H:\ComfyUI-aki-v1.2\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "H:\ComfyUI-aki-v1.2\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "H:\ComfyUI-aki-v1.2\custom_nodes\comfyui_controlnet_aux\node_wrappers\zoe.py", line 17, in execute
    model = ZoeDetector.from_pretrained().to(model_management.get_torch_device())
  File "H:\ComfyUI-aki-v1.2\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\zoe\__init__.py", line 26, in from_pretrained
    model.load_state_dict(torch.load(model_path, map_location=torch.device('cpu'))['model'])
  File "H:\ComfyUI-aki-v1.2\python\lib\site-packages\torch\serialization.py", line 993, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "H:\ComfyUI-aki-v1.2\python\lib\site-packages\torch\serialization.py", line 447, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

2024-09-11 18:32:18,579 - root - INFO - Prompt executed in 4.97 seconds
2024-09-11 18:34:28,729 - root - INFO - got prompt
2024-09-11 18:34:33,590 - root - ERROR - !!! Exception during processing !!! PytorchStreamReader failed reading zip archive: failed finding central directory
2024-09-11 18:34:33,590 - root - ERROR - Traceback (most recent call last):
  File "H:\ComfyUI-aki-v1.2\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "H:\ComfyUI-aki-v1.2\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "H:\ComfyUI-aki-v1.2\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "H:\ComfyUI-aki-v1.2\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "H:\ComfyUI-aki-v1.2\custom_nodes\comfyui_controlnet_aux\node_wrappers\zoe.py", line 17, in execute
    model = ZoeDetector.from_pretrained().to(model_management.get_torch_device())
  File "H:\ComfyUI-aki-v1.2\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\zoe\__init__.py", line 26, in from_pretrained
    model.load_state_dict(torch.load(model_path, map_location=torch.device('cpu'))['model'])
  File "H:\ComfyUI-aki-v1.2\python\lib\site-packages\torch\serialization.py", line 993, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "H:\ComfyUI-aki-v1.2\python\lib\site-packages\torch\serialization.py", line 447, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

2024-09-11 18:34:33,591 - root - INFO - Prompt executed in 4.85 seconds

**Comment by wind2333-hub** [comment]
解决了吗？

**Comment by maolixiao** [comment]
出现同样的情况
![image](https://github.com/user-attachments/assets/6584333b-5cf8-4351-9f63-468a4b459c28)

**Comment by liushijiejob** [comment]
没有解决
















在 2024-09-21 01:21:22，"wind2333-hub" ***@***.***> 写道：

解决了吗？

**Comment by heytony965342** [comment]
网络问题，换稳定节点
