### ISSUE TITLE
Help! Can't install any controlnet

### ISSUE THREAD

**Issue by YarvixPA** [Fannovel16/comfyui_controlnet_aux#463]
Failed to find E:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\hr16/Diffusion-Edge\dsine.pt.
 Downloading from huggingface.co
cacher folder is C:\Users\joela\AppData\Local\Temp, you can change it by custom_tmp_path in config.yaml
E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py:1212: UserWarning: `local_dir_use_symlinks` parameter is deprecated and will be ignored. The process to download files to a local folder has been updated and do not rely on symlinks anymore. You only need to pass a destination folder as`local_dir`.
For more details, check out https://huggingface.co/docs/huggingface_hub/main/en/guides/download#download-files-to-local-folder.
  warnings.warn(
FETCH DATA from: E:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: E:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: E:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
!!! Exception during processing !!! (MaxRetryError("HTTPSConnectionPool(host='cdn-lfs-us-1.hf.co', port=443): Max retries exceeded with url: /repos/09/cd/09cd3c0d1ddc08627f82f13b70ec3277d438edadb4c6d950f415a382f5c509a0/629472c66ea9ec83bab6ba7c957ad7d983bb9c91063a54ad74ff5b8229cbf22f?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27dsine.pt%3B+filename%3D%22dsine.pt%22%3B&Expires=1727957495&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyNzk1NzQ5NX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmhmLmNvL3JlcG9zLzA5L2NkLzA5Y2QzYzBkMWRkYzA4NjI3ZjgyZjEzYjcwZWMzMjc3ZDQzOGVkYWRiNGM2ZDk1MGY0MTVhMzgyZjVjNTA5YTAvNjI5NDcyYzY2ZWE5ZWM4M2JhYjZiYTdjOTU3YWQ3ZDk4M2JiOWM5MTA2M2E1NGFkNzRmZjViODIyOWNiZjIyZj9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=I1FwvfQGx78DRCwGpb3YhkdBkkCp6dUYHnTTrEKN2IclW1SqD9R3X6SeRRz-GZ1BXg5kyTCwESP0QrK18-SO6zYKePnMvxVt58ccNU798w8kY8woKuY6vA5-EDMPiDmjRmwtTBn~ufyeRUQeVb4puJW~qhtuATiH1DWP5ReslchS7gS2eQiIcY6Pz49J8RPIF7pJyQGnlXPKmp5-TWWweQpYLgmaoZBoV6byD76jYlp390EdsCEFTtlKUgLJ5ih31jdPkBGoo541qyktKkdMuZVJ1ixd0LG12lwLHt5tfea08KG8QeMdIeXF6sbaoAnuE2Y4-oHR95jM2-Kz6MM-VQ__&Key-Pair-Id=K24J24Z295AEI9 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D1A2F34950>, 'Connection to cdn-lfs-us-1.hf.co timed out. (connect timeout=10)'))"), '(Request ID: 6d8a4839-d455-4137-a975-f2280854eab2)')
Traceback (most recent call last):
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\urllib3\connection.py", line 196, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\urllib3\connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000001D1A2F34950>, 'Connection to cdn-lfs-us-1.hf.co timed out. (connect timeout=10)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cdn-lfs-us-1.hf.co', port=443): Max retries exceeded with url: /repos/09/cd/09cd3c0d1ddc08627f82f13b70ec3277d438edadb4c6d950f415a382f5c509a0/629472c66ea9ec83bab6ba7c957ad7d983bb9c91063a54ad74ff5b8229cbf22f?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27dsine.pt%3B+filename%3D%22dsine.pt%22%3B&Expires=1727957495&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyNzk1NzQ5NX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmhmLmNvL3JlcG9zLzA5L2NkLzA5Y2QzYzBkMWRkYzA4NjI3ZjgyZjEzYjcwZWMzMjc3ZDQzOGVkYWRiNGM2ZDk1MGY0MTVhMzgyZjVjNTA5YTAvNjI5NDcyYzY2ZWE5ZWM4M2JhYjZiYTdjOTU3YWQ3ZDk4M2JiOWM5MTA2M2E1NGFkNzRmZjViODIyOWNiZjIyZj9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=I1FwvfQGx78DRCwGpb3YhkdBkkCp6dUYHnTTrEKN2IclW1SqD9R3X6SeRRz-GZ1BXg5kyTCwESP0QrK18-SO6zYKePnMvxVt58ccNU798w8kY8woKuY6vA5-EDMPiDmjRmwtTBn~ufyeRUQeVb4puJW~qhtuATiH1DWP5ReslchS7gS2eQiIcY6Pz49J8RPIF7pJyQGnlXPKmp5-TWWweQpYLgmaoZBoV6byD76jYlp390EdsCEFTtlKUgLJ5ih31jdPkBGoo541qyktKkdMuZVJ1ixd0LG12lwLHt5tfea08KG8QeMdIeXF6sbaoAnuE2Y4-oHR95jM2-Kz6MM-VQ__&Key-Pair-Id=K24J24Z295AEI9 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D1A2F34950>, 'Connection to cdn-lfs-us-1.hf.co timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dsine.py", line 21, in execute
    model = DsineDetector.from_pretrained().to(model_management.get_torch_device())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dsine\__init__.py", line 57, in from_pretrained
    model_path = custom_hf_download(pretrained_model_or_path, filename)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\util.py", line 333, in custom_hf_download
    model_path = hf_hub_download(repo_id=pretrained_model_or_path,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1220, in hf_hub_download
    return _hf_hub_download_to_local_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1515, in _hf_hub_download_to_local_dir
    _download_to_tmp_and_move(
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1915, in _download_to_tmp_and_move
    http_get(
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 463, in http_get
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 399, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_http.py", line 66, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\requests\adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='cdn-lfs-us-1.hf.co', port=443): Max retries exceeded with url: /repos/09/cd/09cd3c0d1ddc08627f82f13b70ec3277d438edadb4c6d950f415a382f5c509a0/629472c66ea9ec83bab6ba7c957ad7d983bb9c91063a54ad74ff5b8229cbf22f?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27dsine.pt%3B+filename%3D%22dsine.pt%22%3B&Expires=1727957495&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyNzk1NzQ5NX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmhmLmNvL3JlcG9zLzA5L2NkLzA5Y2QzYzBkMWRkYzA4NjI3ZjgyZjEzYjcwZWMzMjc3ZDQzOGVkYWRiNGM2ZDk1MGY0MTVhMzgyZjVjNTA5YTAvNjI5NDcyYzY2ZWE5ZWM4M2JhYjZiYTdjOTU3YWQ3ZDk4M2JiOWM5MTA2M2E1NGFkNzRmZjViODIyOWNiZjIyZj9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=I1FwvfQGx78DRCwGpb3YhkdBkkCp6dUYHnTTrEKN2IclW1SqD9R3X6SeRRz-GZ1BXg5kyTCwESP0QrK18-SO6zYKePnMvxVt58ccNU798w8kY8woKuY6vA5-EDMPiDmjRmwtTBn~ufyeRUQeVb4puJW~qhtuATiH1DWP5ReslchS7gS2eQiIcY6Pz49J8RPIF7pJyQGnlXPKmp5-TWWweQpYLgmaoZBoV6byD76jYlp390EdsCEFTtlKUgLJ5ih31jdPkBGoo541qyktKkdMuZVJ1ixd0LG12lwLHt5tfea08KG8QeMdIeXF6sbaoAnuE2Y4-oHR95jM2-Kz6MM-VQ__&Key-Pair-Id=K24J24Z295AEI9 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D1A2F34950>, 'Connection to cdn-lfs-us-1.hf.co timed out. (connect timeout=10)'))"), '(Request ID: 6d8a4839-d455-4137-a975-f2280854eab2)')

Prompt executed in 40.96 seconds

**Comment by joelandresnavarro** [comment]
@Fannovel16 @jimlee2048 please help me

**Comment by emogie** [comment]
probably the server was down, try again, if it is still not reachable:
https://huggingface.co/camenduru/DSINE/tree/main
