### ISSUE TITLE
DWPreprocessor

### ISSUE THREAD

**Issue by MONAISMONA** [Fannovel16/comfyui_controlnet_aux#471]
how to resolve this?
![1](https://github.com/user-attachments/assets/8c2cc134-acf1-4a77-90e7-27a215fa1753)
![2](https://github.com/user-attachments/assets/4f3ffc3a-ac7c-4403-8313-6cd4cc99d39e)

# ComfyUI Error Report
## Error Details
- **Node Type:** DWPreprocessor
- **Exception Type:** AssertionError
- **Exception Message:** 
## Stack Trace
```
  File "D:\Stable diffusion\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\Stable diffusion\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\Stable diffusion\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\Stable diffusion\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\Stable diffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 73, in estimate_pose
    model = DwposeDetector.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\Stable diffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\__init__.py", line 244, in from_pretrained
    t = Wholebody(None, pose_model_path, torchscript_device=torchscript_device)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\Stable diffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\wholebody.py", line 74, in __init__
    self.pose.to(torchscript_device)

  File "D:\Stable diffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 1174, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^

  File "D:\Stable diffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)

  File "D:\Stable diffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 829, in _apply
    assert isinstance(param, Parameter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.2-92-ge5ecdfd
- **Arguments:** main.py --directml --use-split-cross-attention --disable-smart-memory --lowvram
- **OS:** nt
- **Python Version:** 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.1+cpu
## Devices

- **Name:** privateuseone
  - **Type:** privateuseone
  - **VRAM Total:** 1073741824
  - **VRAM Free:** 1073741824
  - **Torch VRAM Total:** 1073741824
  - **Torch VRAM Free:** 1073741824

## Logs
```
2024-10-21 04:28:12,470 - root - INFO - Using directml with device: 
2024-10-21 04:28:12,474 - root - INFO - Total VRAM 1024 MB, total RAM 16197 MB
2024-10-21 04:28:12,475 - root - INFO - pytorch version: 2.4.1+cpu
2024-10-21 04:28:12,476 - root - INFO - Set vram state to: LOW_VRAM
2024-10-21 04:28:12,476 - root - INFO - Disabling smart memory management
2024-10-21 04:28:12,476 - root - INFO - Device: privateuseone
2024-10-21 04:28:14,222 - root - INFO - Using split optimization for cross attention
2024-10-21 04:28:15,733 - root - INFO - [Prompt Server] web root: D:\Stable diffusion\ComfyUI\web
2024-10-21 04:28:19,732 - root - INFO - 
Import times for custom nodes:
2024-10-21 04:28:19,732 - root - INFO -    0.0 seconds: D:\Stable diffusion\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-21 04:28:19,732 - root - INFO -    0.0 seconds: D:\Stable diffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-10-21 04:28:19,732 - root - INFO -    0.1 seconds: D:\Stable diffusion\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-21 04:28:19,732 - root - INFO -    0.4 seconds: D:\Stable diffusion\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion
2024-10-21 04:28:19,732 - root - INFO -    1.2 seconds: D:\Stable diffusion\ComfyUI\custom_nodes\ComfyUI-tbox
2024-10-21 04:28:19,732 - root - INFO -    1.8 seconds: D:\Stable diffusion\ComfyUI\custom_nodes\ComfyUI_LayerStyle
2024-10-21 04:28:19,732 - root - INFO - 
2024-10-21 04:28:19,738 - root - INFO - Starting server

2024-10-21 04:28:19,738 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-21 04:29:34,355 - root - INFO - got prompt
2024-10-21 04:29:35,755 - root - ERROR - !!! Exception during processing !!! 
2024-10-21 04:29:35,758 - root - ERROR - Traceback (most recent call last):
  File "D:\Stable diffusion\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\Stable diffusion\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\ComfyUI\custom_nodes\ComfyUI-tbox\nodes\preprocessor\dwpose_node.py", line 74, in estimate_pose
    model = DwposeDetector.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\ComfyUI\custom_nodes\ComfyUI-tbox\src\dwpose\__init__.py", line 244, in from_pretrained
    t = Wholebody(None, pose_model_path, torchscript_device=torchscript_device)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\ComfyUI\custom_nodes\ComfyUI-tbox\src\dwpose\wholebody.py", line 74, in __init__
    self.pose.to(torchscript_device)
  File "D:\Stable diffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 1174, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "D:\Stable diffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 829, in _apply
    assert isinstance(param, Parameter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-10-21 04:29:35,760 - root - INFO - Prompt executed in 1.40 seconds
2024-10-21 04:29:59,829 - root - INFO - got prompt
2024-10-21 04:30:00,082 - root - ERROR - !!! Exception during processing !!! 
2024-10-21 04:30:00,083 - root - ERROR - Traceback (most recent call last):
  File "D:\Stable diffusion\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\Stable diffusion\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\ComfyUI\custom_nodes\ComfyUI-tbox\nodes\preprocessor\dwpose_node.py", line 74, in estimate_pose
    model = DwposeDetector.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\ComfyUI\custom_nodes\ComfyUI-tbox\src\dwpose\__init__.py", line 244, in from_pretrained
    t = Wholebody(None, pose_model_path, torchscript_device=torchscript_device)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\ComfyUI\custom_nodes\ComfyUI-tbox\src\dwpose\wholebody.py", line 74, in __init__
    self.pose.to(torchscript_device)
  File "D:\Stable diffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 1174, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "D:\Stable diffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 829, in _apply
    assert isinstance(param, Parameter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-10-21 04:30:00,086 - root - INFO - Prompt executed in 0.25 seconds
2024-10-21 04:30:29,142 - root - INFO - got prompt
2024-10-21 04:30:49,016 - root - ERROR - !!! Exception during processing !!! 
2024-10-21 04:30:49,017 - root - ERROR - Traceback (most recent call last):
  File "D:\Stable diffusion\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\Stable diffusion\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\ComfyUI\custom_nodes\ComfyUI-tbox\nodes\preprocessor\dwpose_node.py", line 74, in estimate_pose
    model = DwposeDetector.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\ComfyUI\custom_nodes\ComfyUI-tbox\src\dwpose\__init__.py", line 238, in from_pretrained
    t = Wholebody(det_model_path, None, torchscript_device=torchscript_device)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\ComfyUI\custom_nodes\ComfyUI-tbox\src\dwpose\wholebody.py", line 57, in __init__
    self.det.to(torchscript_device)
  File "D:\Stable diffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 1174, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "D:\Stable diffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 829, in _apply
    assert isinstance(param, Parameter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-10-21 04:30:49,020 - root - INFO - Prompt executed in 19.87 seconds
2024-10-21 04:32:25,322 - root - INFO - got prompt
2024-10-21 04:32:26,581 - root - ERROR - !!! Exception during processing !!! 
2024-10-21 04:32:26,583 - root - ERROR - Traceback (most recent call last):
  File "D:\Stable diffusion\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\Stable diffusion\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 73, in estimate_pose
    model = DwposeDetector.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\__init__.py", line 244, in from_pretrained
    t = Wholebody(None, pose_model_path, torchscript_device=torchscript_device)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\wholebody.py", line 74, in __init__
    self.pose.to(torchscript_device)
  File "D:\Stable diffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 1174, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable diffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "D:\Stable diffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 829, in _apply
    assert isinstance(param, Parameter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-10-21 04:32:26,585 - root - INFO - Prompt executed in 1.26 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":13,"last_link_id":10,"nodes":[{"id":4,"type":"ControlNetApplyAdvanced","pos":{"0":362.96435546875,"1":387.3800964355469},"size":{"0":315,"1":186},"flags":{},"order":5,"mode":0,"inputs":[{"name":"positive","type":"CONDITIONING","link":null},{"name":"negative","type":"CONDITIONING","link":null},{"name":"control_net","type":"CONTROL_NET","link":1},{"name":"image","type":"IMAGE","link":3},{"name":"vae","type":"VAE","link":null}],"outputs":[{"name":"positive","type":"CONDITIONING","links":null,"shape":3},{"name":"negative","type":"CONDITIONING","links":null,"shape":3}],"properties":{"Node name for S&R":"ControlNetApplyAdvanced"},"widgets_values":[1,0,1]},{"id":3,"type":"DepthAnythingPreprocessor","pos":{"0":-23.035825729370117,"1":451.3800964355469},"size":{"0":315,"1":82},"flags":{},"order":3,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":2}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[3,4],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"DepthAnythingPreprocessor"},"widgets_values":["depth_anything_vitl14.pth",512]},{"id":2,"type":"ControlNetLoader","pos":{"0":-26,"1":301},"size":{"0":315,"1":58},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"CONTROL_NET","type":"CONTROL_NET","links":[1],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"ControlNetLoader"},"widgets_values":["control_v11f1p_sd15_depth.pth"]},{"id":8,"type":"ControlNetApplyAdvanced","pos":{"0":1301.4715576171875,"1":398.41217041015625},"size":{"0":315,"1":186},"flags":{},"order":9,"mode":0,"inputs":[{"name":"positive","type":"CONDITIONING","link":null},{"name":"negative","type":"CONDITIONING","link":null},{"name":"control_net","type":"CONTROL_NET","link":5},{"name":"image","type":"IMAGE","link":6},{"name":"vae","type":"VAE","link":null}],"outputs":[{"name":"positive","type":"CONDITIONING","links":null,"shape":3},{"name":"negative","type":"CONDITIONING","links":null,"shape":3}],"properties":{"Node name for S&R":"ControlNetApplyAdvanced"},"widgets_values":[1,0,1]},{"id":5,"type":"PreviewImage","pos":{"0":363.96435546875,"1":88.3799819946289},"size":{"0":308.3072509765625,"1":246},"flags":{},"order":6,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":4}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":1,"type":"LoadImage","pos":{"0":-479.03558349609375,"1":323.3800964355469},"size":{"0":315,"1":314},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[2,7],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["ComfyUI_00186_.png","image"]},{"id":9,"type":"Reroute","pos":{"0":-3.1283884048461914,"1":696.5121459960938},"size":[75,26],"flags":{},"order":4,"mode":0,"inputs":[{"name":"","type":"*","link":7}],"outputs":[{"name":"","type":"IMAGE","links":[8],"slot_index":0}],"properties":{"showOutputText":false,"horizontal":false}},{"id":10,"type":"Reroute","pos":{"0":694.2716064453125,"1":703.1121826171875},"size":[75,26],"flags":{},"order":7,"mode":0,"inputs":[{"name":"","type":"*","link":8}],"outputs":[{"name":"","type":"IMAGE","links":[9],"slot_index":0}],"properties":{"showOutputText":false,"horizontal":false}},{"id":7,"type":"DWPreprocessor","pos":{"0":855,"1":370},"size":{"0":315,"1":222},"flags":{},"order":8,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":9}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[6,10],"slot_index":0,"shape":3},{"name":"POSE_KEYPOINT","type":"POSE_KEYPOINT","links":null,"shape":3}],"properties":{"Node name for S&R":"DWPreprocessor"},"widgets_values":["enable","enable","enable",512,"yolox_l.onnx","dw-ll_ucoco_384_bs5.torchscript.pt","disable"]},{"id":11,"type":"PreviewImage","pos":{"0":1299.2716064453125,"1":102.51216888427734},"size":{"0":302.5,"1":231},"flags":{},"order":10,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":10}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":6,"type":"ControlNetLoader","pos":{"0":854,"1":234},"size":{"0":315,"1":58},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"CONTROL_NET","type":"CONTROL_NET","links":[5],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"ControlNetLoader"},"widgets_values":["control_v11p_sd15_openpose.pth"]}],"links":[[1,2,0,4,2,"CONTROL_NET"],[2,1,0,3,0,"IMAGE"],[3,3,0,4,3,"IMAGE"],[4,3,0,5,0,"IMAGE"],[5,6,0,8,2,"CONTROL_NET"],[6,7,0,8,3,"IMAGE"],[7,1,0,9,0,"*"],[8,9,0,10,0,"*"],[9,10,0,7,0,"IMAGE"],[10,7,0,11,0,"IMAGE"]],"groups":[{"title":"Openpose","bounding":[800,-1,902,602],"color":"#b58b2a","font_size":24,"flags":{}},{"title":"Depth","bounding":[-99,1,800,600],"color":"#3f789e","font_size":24,"flags":{}}],"config":{},"extra":{"ds":{"scale":0.7513148009015777,"offset":[491.14008842975403,191.88303471074312]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
###

**Comment by emogie** [comment]
tried a "diffferent" input, output should be the same:
![grafik](https://github.com/user-attachments/assets/56d7141c-c103-49c8-b640-8883769834b2)

from my side it works, please try to redownload the models, probably they are corrupt
