### ISSUE TITLE
Comfyui Controlaux_hed

### ISSUE THREAD

**Issue by CodeOnDope** [Fannovel16/comfyui_controlnet_aux#474]
FETCH DATA from: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ERROR] An error occurred while retrieving information for the 'controlaux_hed' node.
Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

**Comment by delcore50** [comment]
I get this too.

**Comment by emogie** [comment]
+1

**Comment by edulov71** [comment]
Before uninstalling, I tried more reasonable move. At [https://github.com/madtunebk/ComfyUI-ControlnetAux](https://github.com/madtunebk/ComfyUI-ControlnetAux) you have a guide to install dependencies.
Starting from openmim, I did that using pip switches **-U --no-deps** to avoid potential issues with other packages.
Errors with controlnetaux are gone.
