### ISSUE TITLE
ModuleNotFoundError: No module named 'skimage'

### ISSUE THREAD

**Issue by deepakpf** [Fannovel16/comfyui_controlnet_aux#476]
I used stability matrix to install comfyui and this is my first time using it. I got this error when installing this node.

Full error log from comfyui_controlnet_aux: 
Traceback (most recent call last):
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 30, in load_nodes
    module = importlib.import_module(
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 5, in <module>
    from custom_controlnet_aux.dwpose import DwposeDetector, AnimalposeDetector
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\__init__.py", line 17, in <module>
    from .hand import Hand
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\hand.py", line 10, in <module>
    from skimage.measure import label
ModuleNotFoundError: No module named 'skimage'

Traceback (most recent call last):
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 30, in load_nodes
    module = importlib.import_module(
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\pose_keypoint_postprocess.py", line 11, in <module>
    from ..src.custom_controlnet_aux.dwpose import draw_poses, draw_animalposes, decode_json_as_poses
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\__init__.py", line 17, in <module>
    from .hand import Hand
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\dwpose\hand.py", line 10, in <module>
    from skimage.measure import label
ModuleNotFoundError: No module named 'skimage'

[comfyui_controlnet_aux] | INFO -> Some nodes failed to load:
	Failed to import module dwpose because ModuleNotFoundError: No module named 'skimage'
	Failed to import module pose_keypoint_postprocess because ModuleNotFoundError: No module named 'skimage'

**Comment by emogie** [comment]
pip install scikit-image
