### ISSUE TITLE
(IMPORT FAILED): E:\CNTD\ComfyUI\custom_nodes\comfyui_controlnet_aux

### ISSUE THREAD

**Issue by noorhamadani** [Fannovel16/comfyui_controlnet_aux#479]
Guidance required to solve the following issue. its a fresh install and ComfyUI with all the custom nodes required to run 1 workflow. 
Error: 
Cannot import E:\CNTD\ComfyUI\custom_nodes\comfyui_controlnet_aux module for custom nodes: No module named 'custom_albumentations'

Log:

> E:\CNTD>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
> ** ComfyUI startup time: 2024-11-01 15:27:05.118258
> ** Platform: Windows
> ** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
> ** Python executable: E:\CNTD\python_embeded\python.exe
> ** Log path: E:\CNTD\comfyui.log
> 
> Prestartup times for custom nodes:
>    0.0 seconds: E:\CNTD\ComfyUI\custom_nodes\rgthree-comfy
>    0.0 seconds: E:\CNTD\ComfyUI\custom_nodes\ComfyUI-Manager
> 
> Total VRAM 24564 MB, total RAM 32581 MB
> pytorch version: 2.1.0+cu118
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
> Using pytorch cross attention
> [Prompt Server] web root: E:\CNTD\ComfyUI\web
> [Crystools INFO] Crystools version: 1.20.0
> [Crystools INFO] CPU: Intel(R) Core(TM) i9-14900K - Arch: AMD64 - OS: Windows 10
> [Crystools INFO] Pynvml (Nvidia) initialized.
> [Crystools INFO] GPU/s:
> [Crystools INFO] 0) NVIDIA GeForce RTX 4090
> [Crystools INFO] NVIDIA Driver: 561.09
> ### Loading: ComfyUI-Impact-Pack (V5.5.5)
> ### Loading: ComfyUI-Impact-Pack (Subpack: V0.7)
> [Impact Pack] Wildcards loading done.
> ### Loading: ComfyUI-Inspire-Pack (V0.69.3)
> Total VRAM 24564 MB, total RAM 32581 MB
> pytorch version: 2.1.0+cu118
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
> ### Loading: ComfyUI-Manager (V2.8.3)
> ### ComfyUI Revision: 2804 [cc9cf6d1] | Released on '2024-10-31'
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
> no module 'xformers'. Processing without...
> no module 'xformers'. Processing without...
> Traceback (most recent call last):
>   File "E:\CNTD\ComfyUI\nodes.py", line 2012, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "E:\CNTD\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 2, in <module>
>     from .utils import here, define_preprocessor_inputs, INPUT
>   File "E:\CNTD\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 8, in <module>
>     from custom_albumentations.core.keypoints_utils import angle_to_2pi_range
> ModuleNotFoundError: No module named 'custom_albumentations'
> 
> Cannot import E:\CNTD\ComfyUI\custom_nodes\comfyui_controlnet_aux module for custom nodes: No module named 'custom_albumentations'
> Using pytorch cross attention
> Started worker with PID 12644
>  ComfyUI  Fooocus Nodes  : loaded
> 
> [rgthree] Loaded 39 epic nodes.
> [rgthree] NOTE: Will NOT use rgthree's optimized recursive execution as ComfyUI has changed.
> 
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
> WAS Node Suite: OpenCV Python FFMPEG support is enabled
> WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `E:\CNTD\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
> WAS Node Suite: Finished. Loaded 218 nodes successfully.
> 
>         "Art is the lie that enables us to realize the truth." - Pablo Picasso
> 
> 
> Import times for custom nodes:
>    0.0 seconds: E:\CNTD\ComfyUI\custom_nodes\websocket_image_save.py
>    0.0 seconds: E:\CNTD\ComfyUI\custom_nodes\cg-use-everywhere
>    0.0 seconds: E:\CNTD\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG
>    0.0 seconds (IMPORT FAILED): E:\CNTD\ComfyUI\custom_nodes\comfyui_controlnet_aux
>    0.0 seconds: E:\CNTD\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion
>    0.0 seconds: E:\CNTD\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
>    0.0 seconds: E:\CNTD\ComfyUI\custom_nodes\rgthree-comfy
>    0.0 seconds: E:\CNTD\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
>    0.0 seconds: E:\CNTD\ComfyUI\custom_nodes\ComfyUI_essentials
>    0.0 seconds: E:\CNTD\ComfyUI\custom_nodes\ComfyUI-KJNodes
>    0.0 seconds: E:\CNTD\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
>    0.0 seconds: E:\CNTD\ComfyUI\custom_nodes\Fooocus_Nodes
>    0.2 seconds: E:\CNTD\ComfyUI\custom_nodes\ComfyUI-Crystools
>    0.2 seconds: E:\CNTD\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
>    0.3 seconds: E:\CNTD\ComfyUI\custom_nodes\ComfyUI-Manager
>    0.3 seconds: E:\CNTD\ComfyUI\custom_nodes\ComfyUI-SUPIR
>    0.8 seconds: E:\CNTD\ComfyUI\custom_nodes\was-node-suite-comfyui
> 
> Starting server
> 
> To see the GUI go to: http://127.0.0.1:8188
> FETCH DATA from: E:\CNTD\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
> 
>

**Comment by emogie** [comment]
pip install albumentations

**Comment by chenkai89** [comment]
@emogie 执行该命令后还是出现了这个问题
Traceback (most recent call last):
  File "D:\AI\ComfyUI\nodes.py", line 2113, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 2, in <module>
    from .utils import here, define_preprocessor_inputs, INPUT
  File "D:\AI\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 8, in <module>
    from custom_albumentations.core.keypoints_utils import angle_to_2pi_range
ModuleNotFoundError: No module named 'custom_albumentations'

**Comment by chenkai89** [comment]
@emogie 我修改utils文件，改成
from albumentations.core.keypoints_utils import angle_to_2pi_range
from albumentations.core.transforms_interface import KeypointInternalType

又报其他错误：
Traceback (most recent call last):
  File "D:\AI\ComfyUI\nodes.py", line 2113, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 2, in <module>
    from .utils import here, define_preprocessor_inputs, INPUT
ImportError: cannot import name 'here' from 'comfyui_controlnet_aux.utils' (D:\AI\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py)


经查看代码，utils文件内不存在 here, define_preprocessor_inputs, INPUT 函数

**Comment by chenkai89** [comment]
@noorhamadani update code
