### ISSUE TITLE
Error with MIDAS/Fake Scribble - positional argument: 'resolution'

### ISSUE THREAD

**Issue by moon47usaco** [Fannovel16/comfyui_controlnet_aux#49]
got prompt
3
!!! Exception during processing !!!
Traceback (most recent call last):
  File "S:\Ai\Repos\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "S:\Ai\Repos\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "S:\Ai\Repos\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
TypeError: MIDAS_Depth_Map_Preprocessor.execute() missing 1 required positional argument: 'resolution'

**Comment by moon47usaco** [comment]
...
TypeError: Fake_Scribble_Preprocessor.execute() missing 1 required positional argument: 'resolution'

**Comment by freke70** [comment]
Hi, I'm having a similar issue (Zoe_Depth_Map_Preprocessor):

`got prompt
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/root/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/root/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
TypeError: Zoe_Depth_Map_Preprocessor.execute() missing 1 required positional argument: 'resolution'
`

**Comment by yuri-fus** [comment]
Hi ! I've got this error on DWPose node

cv2.error: OpenCV(4.7.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:275: error: (-210:Unsupported format or combination of formats) Failed to parse ONNX model: /home/fus/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts/models--yzd-v--DWPose/snapshots/1a7144101628d69ee7a3768d1ee3a094070dc388/yolox_l.onnx in function 'ONNXImporter'
