### ISSUE TITLE
utils.py BUG - ImportError: cannot import name 'define_preprocessor_inputs' from 'comfyui_controlnet_aux.utils' 

### ISSUE THREAD

**Issue by pendave** [Fannovel16/comfyui_controlnet_aux#494]
`Traceback (most recent call last):
  File "E:\ComfyUI_Portable\ComfyUI\nodes.py", line 2072, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI_Portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 2, in <module>
    from .utils import here, define_preprocessor_inputs, INPUT
ImportError: cannot import name 'define_preprocessor_inputs' from 'comfyui_controlnet_aux.utils' (E:\ComfyUI_Portable\py
thon_embeded\lib\site-packages\filterpy-0.0.15-py3.10.egg\comfyui_controlnet_aux\utils.py)

Cannot import E:\ComfyUI_Portable\ComfyUI\custom_nodes\comfyui_controlnet_aux module for custom nodes: cannot import nam
e 'define_preprocessor_inputs' from 'comfyui_controlnet_aux.utils' (E:\ComfyUI_Portable\python_embeded\lib\site-packages
\filterpy-0.0.15-py3.10.egg\comfyui_controlnet_aux\utils.py)`

What can I do with this Error, it hurts Krita as well.

`2024-12-19 13:27:45,524 ERROR Missing required node InpaintPreprocessor from package ControlNet Preprocessors (https://github.com/Fannovel16/comfyui_controlnet_aux)`

**Comment by pendave** [comment]
I get several utils.py

E:\ComfyUI_Portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py
it has 
`def define_preprocessor_inputs(**arguments):
    return dict(
        required=dict(image=INPUT.IMAGE()),
        optional=arguments
    )`

E:\ComfyUI_Portable\python_embeded\Lib\site-packages\filterpy-0.0.15-py3.10.egg\comfyui_controlnet_aux\utils.py
it does not have `def define_preprocessor_inputs(**arguments):`

So the import stuff got messed up. How to fix it?
