### ISSUE TITLE
nodes doesn't appear after I installed this repo

### ISSUE THREAD

**Issue by HDKKZn** [Fannovel16/comfyui_controlnet_aux#51]
Traceback (most recent call last):
  File "E:\SDUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\SDUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux-main\__init__.py", line 2, in <module>
    from .utils import here, create_node_input_types
  File "E:\SDUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux-main\utils.py", line 4, in <module>    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import E:\SDUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux-main module for custom nodes: No module named 'cv2'

**Comment by Fannovel16** [comment]
How did you install it?

**Comment by world5am** [comment]
This issue is handled in this video. 

https://youtu.be/gS62nkcml0k?si=uwibHlJRrlLFffMh&t=168

**Comment by HDKKZn** [comment]
> This issue is handled in this video.
> 
> https://youtu.be/gS62nkcml0k?si=uwibHlJRrlLFffMh&t=168

it's works!! thanks!!♥

**Comment by HDKKZn** [comment]
> How did you install it?

I downloaded a zip file from GitHub and then extracted it into the "custom_nodes" folder, because of poor internet connection
