### ISSUE TITLE
Import error: module 'cv2.gapi.wip.draw' has no attribute 'Text'

### ISSUE THREAD

**Issue by yeswecan** [Fannovel16/comfyui_controlnet_aux#60]
Installed it via the Manager on OSX. Seems that I have to use another version of cv2?

```
Traceback (most recent call last):
  File "/Users/zebra/Developer/Python/ComfyUI/nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/zebra/Developer/Python/ComfyUI/custom_nodes/comfyui_controlnet_aux/__init__.py", line 2, in <module>
    from .utils import here, create_node_input_types
  File "/Users/zebra/Developer/Python/ComfyUI/custom_nodes/comfyui_controlnet_aux/utils.py", line 4, in <module>
    import cv2
  File "/Users/zebra/Developer/Python/stable-diffusion-webui/venv/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/Users/zebra/Developer/Python/stable-diffusion-webui/venv/lib/python3.10/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/Users/zebra/Developer/Python/stable-diffusion-webui/venv/lib/python3.10/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/zebra/Developer/Python/stable-diffusion-webui/venv/lib/python3.10/site-packages/cv2/typing/__init__.py", line 157, in <module>
    Prim = typing.Union[cv2.gapi.wip.draw.Text, cv2.gapi.wip.draw.Circle, cv2.gapi.wip.draw.Image, cv2.gapi.wip.draw.Line, cv2.gapi.wip.draw.Rect, cv2.gapi.wip.draw.Mosaic, cv2.gapi.wip.draw.Poly]
AttributeError: module 'cv2.gapi.wip.draw' has no attribute 'Text'
```

**Comment by Fannovel16** [comment]
The reason may be opencv dependecies conflicts ig. Try these command:
```
pip uninstall -y opencv-python opencv-contrib-python opencv-python-headless 
pip install opencv-python==4.7.0.72
```

**Comment by yeswecan** [comment]
Thanks! This worked. Tried reinstalling opencv but trying the previous version, as you suggested, did the trick!

**Comment by rovo79** [comment]
This issue keeps resurfacing for me anytime I update the nodes. When it does happen, it seems to involve comfyui_controlnet_aux, comfyUI-Impact-Pack,  was-node-suite-comfyui (WASasquatch/was-node-suite-comfyui#251); but I'm not sure which one is the source of the cause. I just keep rerunning the above suggested uninstall/install opencv to get things working again.

**Comment by Thanh1122kkll** [comment]
fannovel's method not working. installing WAS -> help for sure

**Comment by 1826133674** [comment]
It Works! Thank you very much!

**Comment by 1826133674** [comment]
> The reason may be opencv dependecies conflicts ig. Try these command:
> 
> ```
> pip uninstall -y opencv-python opencv-contrib-python opencv-python-headless 
> pip install opencv-python==4.7.0.72
> ```

Than you very much!
