### ISSUE TITLE
Error occurred when executing UniFormer-SemSegPreprocessor

### ISSUE THREAD

**Issue by webe998** [Fannovel16/comfyui_controlnet_aux#8]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\uniformer.py", line 18, in semantic_segmentate
    out = common_annotator_call(model, image)
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 28, in common_annotator_call
    np_result = model(np_image, output_type="np", **kwargs)
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\uniformer\__init__.py", line 83, in __call__
    detected_map = self._inference(input_image)
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\uniformer\__init__.py", line 61, in _inference
    result = inference_segmentor(self.model, img)
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\uniformer\inference.py", line 94, in inference_segmentor
    data = collate([data], samples_per_gpu=1)
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mmpkg\mmcv\parallel\collate.py", line 79, in collate
    return {
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mmpkg\mmcv\parallel\collate.py", line 80, in <dictcomp>
    key: collate([d[key] for d in batch], samples_per_gpu)
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mmpkg\mmcv\parallel\collate.py", line 77, in collate
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mmpkg\mmcv\parallel\collate.py", line 77, in <listcomp>
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mmpkg\mmcv\parallel\collate.py", line 84, in collate
    return default_collate(batch)
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\utils\data\_utils\collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\utils\data\_utils\collate.py", line 150, in collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'custom_mmpkg.mmcv.parallel.data_container.DataContainer'>

**Comment by Piscabo** [comment]
5 of the nodes from the 'test_cn_aux_full.json' failed. The others were all successful. 
 File "A:\AI_Files\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\nodes\edge_line.py", line 89, in transform_scribble
    np_detected_map_list = common_annotator_call(hed_v1.HEDdetector(), image)
NameError: name 'hed_v1' is not defined

File "A:\AI_Files\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\nodes\normal_depth_map.py", line 42, in estimate_normal
    depth_map_np, normal_map_np = common_annotator_call(midas.MidasDetector(), image, a, bg_threshold)
NameError: name 'midas' is not defined

File "A:\AI_Files\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mmpkg\mmcv\utils\registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "EncoderDecoder: 'UniFormer is not in the models registry'"

File "A:\AI_Files\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mmpkg\mmcv\utils\registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'UniFormer is not in the models registry'

 File "A:\AI_Files\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mmpkg\mmcv\utils\registry.py", line 246, in _register_module
    raise KeyError(f'{name} is already registered '
KeyError: 'DeconvModule is already registered in upsample layer'

**Comment by Fannovel16** [comment]
@Piscabo You need to remove the old comfy_controlnet_preprocessors as it will make some conflicts with this repo.

**Comment by youyegit** [comment]
all nodes work well except UniFormer-SemSegPreprocessor:
the error shows:

Error occurred when executing UniFormer-SemSegPreprocessor:

top_pool_forward miss in module _ext

File "E:\AI\SD\sd_ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "E:\AI\SD\sd_ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "E:\AI\SD\sd_ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "E:\AI\SD\sd_ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\uniformer.py", line 15, in semantic_segmentate
from controlnet_aux.uniformer import UniformerSegmentor
File "E:\AI\SD\sd_ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\uniformer\__init__.py", line 2, in
from .inference import init_segmentor, inference_segmentor, show_result_pyplot
File "E:\AI\SD\sd_ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\uniformer\inference.py", line 8, in
from custom_mmpkg.custom_mmseg.models import build_segmentor
File "E:\AI\SD\sd_ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mmpkg\custom_mmseg\models\__init__.py", line 4, in
from .decode_heads import * # noqa: F401,F403
File "E:\AI\SD\sd_ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mmpkg\custom_mmseg\models\decode_heads\__init__.py", line 4, in
from .cc_head import CCHead
File "E:\AI\SD\sd_ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mmpkg\custom_mmseg\models\decode_heads\cc_head.py", line 7, in
from custom_mmpkg.custom_mmcv.ops import CrissCrossAttention
File "E:\AI\SD\sd_ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mmpkg\custom_mmcv\ops\__init__.py", line 10, in
from .corner_pool import CornerPool
File "E:\AI\SD\sd_ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mmpkg\custom_mmcv\ops\corner_pool.py", line 8, in
ext_module = ext_loader.load_ext('_ext', [
File "E:\AI\SD\sd_ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mmpkg\custom_mmcv\utils\ext_loader.py", line 15, in load_ext
assert hasattr(ext, fun), f'{fun} miss in module {name}'
