### ISSUE TITLE
No module 'mmcv and 'addict'

### ISSUE THREAD

**Issue by cerarslan** [Fannovel16/comfyui_controlnet_aux#9]
I installed and I checked my dependencies. I can run on the page but I see this error on my terminal: 

Full error log from comfyui_controlnet_aux:
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\uniformer\inference.py", line 5, in <module>
    import mmcv as mmcv
ModuleNotFoundError: No module named 'mmcv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 23, in load_nodes
    module = importlib.import_module(
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\uniformer.py", line 2, in <module>
    from controlnet_aux.uniformer import UniformerSegmentor
  File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\uniformer\__init__.py", line 2, in <module>
    from .inference import init_segmentor, inference_segmentor, show_result_pyplot
  File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\uniformer\inference.py", line 11, in <module>
    import custom_mmpkg.mmcv as mmcv
  File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mmpkg\mmcv\__init__.py", line 4, in <module>
    from .fileio import *
  File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mmpkg\mmcv\fileio\__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mmpkg\mmcv\fileio\file_client.py", line 15, in <module>
    from custom_mmpkg.mmcv.utils.misc import has_method
  File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mmpkg\mmcv\utils\__init__.py", line 3, in <module>
    from .config import Config, ConfigDict, DictAction
  File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mmpkg\mmcv\utils\config.py", line 16, in <module>
    from addict import Dict
ModuleNotFoundError: No module named 'addict'

[comfyui_controlnet_aux] | STATUS -> Some nodes failed to load:
        Failed to import module uniformer because ModuleNotFoundError: No module named 'addict'

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/Fannovel16/comfyui_controlnet_aux/issues)

**Comment by JasonS09** [comment]
Got the same issue, I checked I correctly installed dependencies and have updated my local repo.

**Comment by cerarslan** [comment]
Additionally I find this discussion https://github.com/open-mmlab/mmcv/issues/1386 and I tried: 

'for me, I have pytorch 2.0 and c 11.8, so:
pip install mmcv==2.0.0 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.0/index.html' 

and still got the same error

**Comment by Fannovel16** [comment]
@JasonS09 @cerarslan I just removed the usage of offical mmcv at https://github.com/Fannovel16/comfyui_controlnet_aux/commit/21e5b60c15a5c6e17d997362fb5b459d19162adc. Can yall try again?

**Comment by JasonS09** [comment]
It seems to be working now.
