### ISSUE TITLE
ConnectionResetError

### ISSUE THREAD

**Issue by mccgentil** [Fannovel16/comfyui_controlnet_aux#92]
I attempted to install comfyui_controlnet_aux via Google Colab from ComfyUI-Manager, but I encountered the following error logs. The installation could not be completed (however, the uninstall button for ComfyUI-Manager does appear). Is there any way to resolve this issue? Your assistance is greatly appreciated.

```
# ComfyUI-Manager: EXECUTE => ['/usr/bin/python3', '-m', 'pip', 'install', 'addict']
 Requirement already satisfied: addict in /usr/local/lib/python3.10/dist-packages (2.4.0)
Installation was successful.
After restarting ComfyUI, please refresh the browser.
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/content/drive/MyDrive/ComfyUI/server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "/content/drive/MyDrive/ComfyUI/server.py", line 100, in websocket_handler
    await ws.prepare(request)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_ws.py", line 138, in prepare
    payload_writer = await super().prepare(request)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_response.py", line 421, in prepare
    return await self._start(request)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_response.py", line 429, in _start
    await self._write_headers()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_response.py", line 502, in _write_headers
    await writer.write_headers(status_line, self._headers)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/http_writer.py", line 130, in write_headers
    self._write(buf)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/http_writer.py", line 75, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

**Comment by mccgentil** [comment]
I apologize for the inconvenience. The issue has been resolved.
