### ISSUE TITLE
Error regarding onnxruntime！！！

### ISSUE THREAD

**Issue by yinghanzi** [Fannovel16/comfyui_controlnet_aux#98]
DWPose: Onnxruntime with acceleration providers detected. Caching sessions (might take around half a minute)...
2023-11-05 23:22:05.7299292 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\sunny\Documents\anaconda3\envs\comfyui\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:739 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
2023-11-05 23:22:05.8159495 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\sunny\Documents\anaconda3\envs\comfyui\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Full error log from comfyui_controlnet_aux:
Traceback (most recent call last):
  File "C:\Users\sunny\Documents\anaconda3\envs\comfyui\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\sunny\Documents\anaconda3\envs\comfyui\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 463, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:739 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sunny\Documents\comfyui\custom_nodes\comfyui_controlnet_aux\__init__.py", line 34, in load_nodes
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Documents\anaconda3\envs\comfyui\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\sunny\Documents\comfyui\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 22, in <module>
    model = DwposeDetector.from_pretrained(DWPOSE_MODEL_NAME, cache_dir=annotator_ckpts_path)        
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^        
  File "C:\Users\sunny\Documents\comfyui\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\__init__.py", line 167, in from_pretrained
    return cls(Wholebody(det_model_path, pose_model_path))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Documents\comfyui\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\wholebody.py", line 34, in __init__
    ort_session_det = ort.InferenceSession(onnx_det, providers=SUPPORT_PROVIDERS)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Documents\anaconda3\envs\comfyui\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 430, in __init__
    raise fallback_error from e
  File "C:\Users\sunny\Documents\anaconda3\envs\comfyui\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 425, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "C:\Users\sunny\Documents\anaconda3\envs\comfyui\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 463, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:739 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

[comfyui_controlnet_aux] | INFO -> Some nodes failed to load:
        Failed to import module dwpose because

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/Fannovel16/comfyui_controlnet_aux/issues)
2023-11-05 23:22:06.0748814 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\sunny\Documents\anaconda3\envs\comfyui\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2023-11-05 23:22:06.1582867 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\sunny\Documents\anaconda3\envs\comfyui\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

[comfyui_controlnet_aux] | INFO -> Some nodes failed to load:
        Failed to import module dwpose because
_________________

This problem has been bothering me all along, it happens every time I start. How can I solve it?

**Comment by Fannovel16** [comment]
@yinghanzi What CUDA version are you using?

**Comment by yinghanzi** [comment]
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Torch version: 2.1.0+cu121
DWPose: Onnxruntime with acceleration providers detected. Caching sessions (might take around half a minute)...

--------------------------------------------------------
Since installing this plugin, every startup has been particularly slow！

Also reporting various errors！！！

-----------------------------

DWPose: Onnxruntime with acceleration providers detected. Caching sessions (might take around half a minute)...
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=100)"), '(Request ID: a11588b5-852b-4310-987e-213bdf8c922d)')' thrown while requesting HEAD https://huggingface.co/yzd-v/DWPose/resolve/main/yolox_l.onnx


Full error log from comfyui_controlnet_aux:
Traceback (most recent call last):
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\urllib3\connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\urllib3\connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\urllib3\connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\urllib3\connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\urllib3\util\ssl_.py", line 471, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\urllib3\util\ssl_.py", line 515, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\ssl.py", line 1108, in _create
    self.do_handshake()
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:989: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\urllib3\util\util.py", line 39, in reraise
    raise value
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\urllib3\connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\urllib3\connectionpool.py", line 492, in _make_request
    raise new_e
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\urllib3\connectionpool.py", line 470, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\urllib3\connectionpool.py", line 371, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=100)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\huggingface_hub\file_download.py", line 1232, in hf_hub_download
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\huggingface_hub\file_download.py", line 1599, in get_hf_file_metadata
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\huggingface_hub\file_download.py", line 417, in _request_wrapper
    response = _request_wrapper(
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\huggingface_hub\file_download.py", line 452, in _request_wrapper
    return http_backoff(
           ^^^^^^^^^^^^^
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\huggingface_hub\utils\_http.py", line 274, in http_backoff
    raise err
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\huggingface_hub\utils\_http.py", line 258, in http_backoff
    response = session.request(method=method, url=url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\huggingface_hub\utils\_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: (ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=100)"), '(Request ID: a11588b5-852b-4310-987e-213bdf8c922d)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sunny\Documents\comfyui\custom_nodes\comfyui_controlnet_aux\__init__.py", line 34, in load_nodes
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\sunny\Documents\comfyui\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 22, in <module>
    model = DwposeDetector.from_pretrained(DWPOSE_MODEL_NAME, cache_dir=annotator_ckpts_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Documents\comfyui\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\__init__.py", line 164, in from_pretrained
    det_model_path = custom_hf_download(pretrained_model_or_path, det_filename, cache_dir=cache_dir)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Documents\comfyui\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\util.py", line 199, in custom_hf_download
    model_path = hf_hub_download(repo_id=pretrained_model_or_path,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\.conda\envs\comfyui\Lib\site-packages\huggingface_hub\file_download.py", line 1349, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.



[comfyui_controlnet_aux] | INFO -> Some nodes failed to load:
        Failed to import module dwpose because huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/Fannovel16/comfyui_controlnet_aux/issues)

**Comment by Layer-norm** [comment]
please ckeeck your modle path, if you manal download them.
![ckpts](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/140777998/df0956ca-6602-4fdb-9d77-94203d623e09)

Besides, please check  whether your cudnn version matches your cuda version. I suspect that you didn't update your cudnn after update your cuda. My system with pytorch2.1.0+cu12.1 works fine.

![my system](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/140777998/0c2e50c5-61c6-4215-8d01-7a0d63915550)
